import type { UploadPolicy } from './types.js';
import { sanitizeFileName } from './types.js';

const env = process.env['NODE_ENV'] === 'production' ? 'prod' : 'dev';

export const messageAttachmentPolicy: UploadPolicy = {
  policyId: 'message_attachment',
  feature: 'message_attachment',
  backend: 'r2-private',
  keyNamespace: 'communications/messages',
  allowedMimeTypes: [
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'image/heif',
    'image/tiff',
    'image/bmp',
    'image/dicom-rle',
    'video/mp4',
    'video/mpeg',
    'video/quicktime',
    'video/webm',
    'video/x-msvideo',
    'video/x-matroska',
    'audio/mpeg',
    'audio/mp4',
    'audio/aac',
    'audio/wav',
    'audio/x-wav',
    'audio/webm',
    'application/pdf',
    'application/rtf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.ms-powerpoint',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.oasis.opendocument.presentation',
    'application/dicom',
    'application/x-dicom',
    'application/zip',
    'application/x-zip-compressed',
    'application/x-7z-compressed',
    'application/vnd.rar',
    'application/x-rar-compressed',
    'text/plain',
    'text/csv',
    'text/rtf',
    'text/markdown',
  ],
  maxFileSize: 100 * 1024 * 1024,
  buildStorageKey: (input, assetId) =>
    `crm/${env}/communications/messages/${input.ownerId}/${assetId}/${sanitizeFileName(input.fileName)}`,
};
