-- Generated by scripts/export-full-bootstrap-sql.mjs
-- Do not hand-edit this file. Re-run pnpm db:export:full instead.

-- Fresh local PostgreSQL needs pgcrypto for gen_random_uuid().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Supabase provides auth.uid(). Plain PostgreSQL does not.
-- This shim keeps local imports working without changing app behavior.
CREATE SCHEMA IF NOT EXISTS auth;
CREATE OR REPLACE FUNCTION auth.uid()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

-- Base schema snapshot from Drizzle introspection.
CREATE TYPE "public"."AISummaryStatus" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');--> statement-breakpoint
CREATE TYPE "public"."AuditEvent" AS ENUM('DOC_UPLOAD', 'DOC_VIEW', 'DOC_DOWNLOAD', 'DOC_DELETE', 'DOC_SHARE_LINK_CREATED', 'DOC_SHARE_LINK_USED', 'CASE_CREATED', 'CASE_ASSIGNED', 'CASE_REVOKED', 'CASE_STATUS_CHANGED', 'USER_LOGIN', 'USER_LOGOUT');--> statement-breakpoint
CREATE TYPE "public"."CaseStage" AS ENUM('PENDING_ASSIGNMENT', 'TRANSFERRED_TO_HOSPITAL', 'HOSPITAL_CONTACTED', 'CONSULTATION_SCHEDULED', 'IN_TREATMENT', 'TREATMENT_COMPLETED');--> statement-breakpoint
CREATE TYPE "public"."CaseStatus" AS ENUM('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'ARCHIVED');--> statement-breakpoint
CREATE TYPE "public"."ConsultationStatus" AS ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW');--> statement-breakpoint
CREATE TYPE "public"."ConversationAssistantMode" AS ENUM('AI_ACTIVE', 'HUMAN_TAKEOVER');--> statement-breakpoint
CREATE TYPE "public"."ConversationCategory" AS ENUM('HOSPITAL', 'PATIENT', 'ADMIN_HOSPITAL', 'ADMIN_PATIENT', 'HOSPITAL_PATIENT');--> statement-breakpoint
CREATE TYPE "public"."DocumentStatus" AS ENUM('PENDING', 'ACTIVE', 'DELETED');--> statement-breakpoint
CREATE TYPE "public"."DocumentType" AS ENUM('LAB', 'IMAGING', 'DISCHARGE', 'PRESCRIPTION', 'ID', 'DIAGNOSIS', 'QUOTE', 'INVITATION', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."HospitalStatus" AS ENUM('ACTIVE', 'PENDING', 'INACTIVE');--> statement-breakpoint
CREATE TYPE "public"."HospitalType" AS ENUM('COSMETIC', 'REGULAR');--> statement-breakpoint
CREATE TYPE "public"."MessageType" AS ENUM('TEXT', 'IMAGE', 'FILE', 'SYSTEM');--> statement-breakpoint
CREATE TYPE "public"."ModerationStatus" AS ENUM('ALLOWED', 'BLOCKED', 'REVIEW');--> statement-breakpoint
CREATE TYPE "public"."ProgressType" AS ENUM('STATUS_CHANGE', 'DOCUMENT_UPLOAD', 'VIDEO_CONSULTATION', 'MESSAGE', 'APPOINTMENT');--> statement-breakpoint
CREATE TYPE "public"."RiskLevel" AS ENUM('LOW', 'MEDIUM', 'HIGH');--> statement-breakpoint
CREATE TYPE "public"."Sensitivity" AS ENUM('PHI_HIGH', 'PHI_MED', 'PHI_LOW');--> statement-breakpoint
CREATE TYPE "public"."UserRole" AS ENUM('ADMIN', 'HOSPITAL', 'PATIENT');--> statement-breakpoint
CREATE TABLE "_prisma_migrations" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"checksum" varchar(64) NOT NULL,
	"finished_at" timestamp with time zone,
	"migration_name" varchar(255) NOT NULL,
	"logs" text,
	"rolled_back_at" timestamp with time zone,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"applied_steps_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cases" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_number" varchar(50) NOT NULL,
	"patient_id" uuid NOT NULL,
	"assigned_hospital_id" uuid,
	"patient_name" varchar(100) NOT NULL,
	"patient_country" varchar(100),
	"patient_language" varchar(10) DEFAULT 'en' NOT NULL,
	"primary_diagnosis" text,
	"diagnosis_code" varchar(50),
	"symptoms" jsonb,
	"medical_history" text,
	"ai_summary_zh" text,
	"ai_summary_en" text,
	"risk_level" "RiskLevel",
	"status" "CaseStatus" DEFAULT 'ACTIVE' NOT NULL,
	"stage" "CaseStage" DEFAULT 'PENDING_ASSIGNMENT' NOT NULL,
	"assigned_at" timestamp(6),
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"uploaded_by_id" uuid NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"file_size" integer NOT NULL,
	"mime_type" varchar(100) NOT NULL,
	"storage_key" varchar(500) NOT NULL,
	"sha256" varchar(64),
	"document_type" "DocumentType" NOT NULL,
	"sensitivity" "Sensitivity" DEFAULT 'PHI_HIGH' NOT NULL,
	"language" varchar(10) DEFAULT 'en' NOT NULL,
	"is_translated" boolean DEFAULT false NOT NULL,
	"source_doc_id" uuid,
	"version" integer DEFAULT 1 NOT NULL,
	"status" "DocumentStatus" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"hospital_id" uuid,
	"event" "AuditEvent" NOT NULL,
	"case_id" uuid,
	"document_id" uuid,
	"ip_address" varchar(50),
	"user_agent" text,
	"metadata" jsonb,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "case_progress" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"title" varchar(200) NOT NULL,
	"description" text,
	"progress_type" "ProgressType" NOT NULL,
	"video_summary" jsonb,
	"recorded_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"recorded_by_id" uuid
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(100) NOT NULL,
	"role" "UserRole" DEFAULT 'PATIENT' NOT NULL,
	"hospital_id" uuid,
	"avatar_url" varchar(500),
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"last_login_at" timestamp(6),
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL,
	"patient_code" varchar(20),
	"country" varchar(100),
	"preferred_language" varchar(10) DEFAULT 'zh' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"sender_id" uuid NOT NULL,
	"content" text NOT NULL,
	"original_language" varchar(10) DEFAULT 'en' NOT NULL,
	"translated_content" text,
	"message_type" "MessageType" DEFAULT 'TEXT' NOT NULL,
	"moderation_status" "ModerationStatus" DEFAULT 'ALLOWED' NOT NULL,
	"attachments" jsonb,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"ai_summary" text
);
--> statement-breakpoint
CREATE TABLE "hospitals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(200) NOT NULL,
	"name_en" varchar(200),
	"address" text,
	"phone" varchar(50),
	"email" varchar(255),
	"description" text,
	"logo_url" varchar(500),
	"specialties" jsonb,
	"status" "HospitalStatus" DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL,
	"type" "HospitalType" DEFAULT 'COSMETIC' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consultations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid NOT NULL,
	"hospital_id" uuid NOT NULL,
	"patient_id" uuid NOT NULL,
	"doctor_id" uuid,
	"status" "ConsultationStatus" DEFAULT 'SCHEDULED' NOT NULL,
	"scheduled_at" timestamp(6) NOT NULL,
	"started_at" timestamp(6),
	"ended_at" timestamp(6),
	"duration_minutes" integer DEFAULT 30 NOT NULL,
	"actual_duration" integer,
	"consultation_link" varchar(500),
	"ai_translation" boolean DEFAULT false NOT NULL,
	"patient_language" varchar(10) DEFAULT 'en' NOT NULL,
	"notes" text,
	"video_storage_key" varchar(500),
	"video_size" bigint,
	"video_duration" integer,
	"video_thumbnail" varchar(500),
	"video_uploaded_at" timestamp(6),
	"ai_summary" jsonb,
	"ai_summary_created_at" timestamp(6),
	"ai_summary_status" "AISummaryStatus" DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consultation_transcripts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"consultation_id" uuid NOT NULL,
	"original_lang" varchar(10) DEFAULT 'en' NOT NULL,
	"translated_lang" varchar(10),
	"entries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"generated_at" timestamp(6),
	"created_at" timestamp(6) DEFAULT now() NOT NULL,
	"updated_at" timestamp(6) DEFAULT now() NOT NULL,
	CONSTRAINT "consultation_transcripts_consultation_id_key" UNIQUE("consultation_id")
);
--> statement-breakpoint
ALTER TABLE "consultation_transcripts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "translation_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hospital_type" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"source_language" text DEFAULT 'zh' NOT NULL,
	"target_language" text NOT NULL,
	"status" text DEFAULT 'pending',
	"error_message" text,
	"retry_count" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "translation_tasks_hospital_type_entity_type_entity_id_sourc_key" UNIQUE("hospital_type","entity_type","entity_id","source_language","target_language")
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"case_id" uuid,
	"category" "ConversationCategory" NOT NULL,
	"title" varchar(200),
	"hospital_id" uuid,
	"assistant_mode" "ConversationAssistantMode" DEFAULT 'AI_ACTIVE' NOT NULL,
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL,
	"last_message_id" uuid,
	"last_message_at" timestamp with time zone,
	"last_message_preview" text,
	"last_sender_id" uuid
);
--> statement-breakpoint
CREATE TABLE "hospital_registration_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hospital_id" uuid NOT NULL,
	"token" varchar(100) NOT NULL,
	"email" varchar(255) NOT NULL,
	"expires_at" timestamp(6) NOT NULL,
	"used_at" timestamp(6),
	"keycloak_user_id" varchar(100),
	"created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp(6) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_assigned_hospital_id_fkey" FOREIGN KEY ("assigned_hospital_id") REFERENCES "public"."hospitals"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cases" ADD CONSTRAINT "cases_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_source_doc_id_fkey" FOREIGN KEY ("source_doc_id") REFERENCES "public"."documents"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "case_progress" ADD CONSTRAINT "case_progress_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_hospital_id_fkey" FOREIGN KEY ("hospital_id") REFERENCES "public"."hospitals"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "consultations" ADD CONSTRAINT "consultations_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "consultations" ADD CONSTRAINT "consultations_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "consultation_transcripts" ADD CONSTRAINT "consultation_transcripts_consultation_id_fkey" FOREIGN KEY ("consultation_id") REFERENCES "public"."consultations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "public"."cases"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
-- NOTE: conversations_last_message_id_fkey (last_message_id -> messages.id) intentionally omitted
-- from Drizzle schema to break circular FK (messages <-> conversations). Constraint exists in DB.
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_last_sender_id_fkey" FOREIGN KEY ("last_sender_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hospital_registration_tokens" ADD CONSTRAINT "hospital_registration_tokens_hospital_id_fkey" FOREIGN KEY ("hospital_id") REFERENCES "public"."hospitals"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "cases_assigned_hospital_id_idx" ON "cases" USING btree ("assigned_hospital_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "cases_case_number_idx" ON "cases" USING btree ("case_number" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "cases_case_number_key" ON "cases" USING btree ("case_number" text_ops);--> statement-breakpoint
CREATE INDEX "cases_patient_id_idx" ON "cases" USING btree ("patient_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "cases_stage_idx" ON "cases" USING btree ("stage" enum_ops);--> statement-breakpoint
CREATE INDEX "cases_status_idx" ON "cases" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "documents_case_id_idx" ON "documents" USING btree ("case_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "documents_document_type_idx" ON "documents" USING btree ("document_type" enum_ops);--> statement-breakpoint
CREATE INDEX "documents_status_idx" ON "documents" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "documents_storage_key_key" ON "documents" USING btree ("storage_key" text_ops);--> statement-breakpoint
CREATE INDEX "documents_uploaded_by_id_idx" ON "documents" USING btree ("uploaded_by_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_case_id_idx" ON "audit_logs" USING btree ("case_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_document_id_idx" ON "audit_logs" USING btree ("document_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_event_idx" ON "audit_logs" USING btree ("event" enum_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_hospital_id_idx" ON "audit_logs" USING btree ("hospital_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "audit_logs_user_id_idx" ON "audit_logs" USING btree ("user_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "case_progress_case_id_idx" ON "case_progress" USING btree ("case_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "case_progress_progress_type_idx" ON "case_progress" USING btree ("progress_type" enum_ops);--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_key" ON "users" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "users_hospital_id_idx" ON "users" USING btree ("hospital_id" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "users_patient_code_key" ON "users" USING btree ("patient_code" text_ops);--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_messages_ai_summary" ON "messages" USING btree ("id" uuid_ops) WHERE (ai_summary IS NOT NULL);--> statement-breakpoint
CREATE INDEX "idx_messages_conversation_time" ON "messages" USING btree ("conversation_id" uuid_ops,"created_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "messages_conversation_id_idx" ON "messages" USING btree ("conversation_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "messages_created_at_idx" ON "messages" USING btree ("created_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "messages_sender_id_idx" ON "messages" USING btree ("sender_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "hospitals_status_idx" ON "hospitals" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "hospitals_type_idx" ON "hospitals" USING btree ("type" enum_ops);--> statement-breakpoint
CREATE INDEX "consultations_case_id_idx" ON "consultations" USING btree ("case_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "consultations_hospital_id_idx" ON "consultations" USING btree ("hospital_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "consultations_patient_id_idx" ON "consultations" USING btree ("patient_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "consultations_scheduled_at_idx" ON "consultations" USING btree ("scheduled_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "consultations_status_idx" ON "consultations" USING btree ("status" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_consultations_translation_scheduled" ON "consultations" USING btree ("hospital_id" uuid_ops) WHERE ((ai_translation = true) AND (status = 'SCHEDULED'::"ConsultationStatus"));--> statement-breakpoint
CREATE INDEX "idx_consultation_transcripts_status" ON "consultation_transcripts" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "idx_translation_tasks_created_at" ON "translation_tasks" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_translation_tasks_entity" ON "translation_tasks" USING btree ("entity_type" text_ops,"entity_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_translation_tasks_hospital_type" ON "translation_tasks" USING btree ("hospital_type" text_ops);--> statement-breakpoint
CREATE INDEX "idx_translation_tasks_pending" ON "translation_tasks" USING btree ("status" text_ops,"created_at" timestamptz_ops) WHERE (status = 'pending'::text);--> statement-breakpoint
CREATE INDEX "idx_translation_tasks_status" ON "translation_tasks" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "conversations_case_id_idx" ON "conversations" USING btree ("case_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "conversations_category_idx" ON "conversations" USING btree ("category" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_conversations_hospital_category_time" ON "conversations" USING btree ("hospital_id" uuid_ops,"category" enum_ops,"last_message_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "hospital_registration_tokens_expires_at_idx" ON "hospital_registration_tokens" USING btree ("expires_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "hospital_registration_tokens_hospital_id_idx" ON "hospital_registration_tokens" USING btree ("hospital_id" uuid_ops);--> statement-breakpoint
CREATE INDEX "hospital_registration_tokens_token_idx" ON "hospital_registration_tokens" USING btree ("token" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "hospital_registration_tokens_token_key" ON "hospital_registration_tokens" USING btree ("token" text_ops);--> statement-breakpoint
CREATE POLICY "Admins can manage all consultation transcripts" ON "consultation_transcripts" AS PERMISSIVE FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM users
  WHERE ((users.id = auth.uid()) AND (users.role = 'ADMIN'::"UserRole")))));--> statement-breakpoint
CREATE POLICY "Hospital users can view their consultation transcripts" ON "consultation_transcripts" AS PERMISSIVE FOR SELECT TO public;

-- Follow-up migrations in the same lexical order as database/migrate.ts.

-- Migration: 001_ai_summary_columns.sql
-- Phase 2A: Consolidate AI summary columns
ALTER TABLE cases ADD COLUMN IF NOT EXISTS ai_summary TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS ai_summary_language VARCHAR(10);

-- Migrate existing data (prefer Chinese, fall back to English)
UPDATE cases
SET ai_summary = COALESCE(ai_summary_zh, ai_summary_en),
    ai_summary_language = CASE
      WHEN ai_summary_zh IS NOT NULL THEN 'zh'
      WHEN ai_summary_en IS NOT NULL THEN 'en'
      ELSE NULL
    END
WHERE ai_summary IS NULL
  AND (ai_summary_zh IS NOT NULL OR ai_summary_en IS NOT NULL);

-- Keep old columns for now (drop in future phase after verification)

-- Migration: 0024_unified_translation.sql
-- Extend translation_tasks
ALTER TABLE translation_tasks
  ADD COLUMN IF NOT EXISTS source_db VARCHAR(32) NOT NULL DEFAULT 'crm',
  ADD COLUMN IF NOT EXISTS fields_to_translate JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS target_languages TEXT[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS detected_language VARCHAR(10);

ALTER TABLE translation_tasks ALTER COLUMN hospital_type DROP NOT NULL;
ALTER TABLE translation_tasks ALTER COLUMN target_language DROP NOT NULL;

-- Backfill new columns from the legacy one-row-per-target-language model.
UPDATE translation_tasks
SET
  source_db = 'crm',
  target_languages = CASE
    WHEN target_language IS NULL THEN '{}'::text[]
    ELSE ARRAY[target_language]
  END
WHERE target_languages = '{}'::text[];

-- Merge duplicate pending/processing rows created under the old per-language queue model
-- into the new unified one-row-per-entity model.
WITH grouped AS (
  SELECT
    entity_type,
    entity_id,
    CASE
      WHEN COUNT(DISTINCT hospital_type) = 1 THEN MIN(hospital_type)
      ELSE NULL
    END AS merged_hospital_type,
    CASE
      WHEN COUNT(DISTINCT source_language) = 1 THEN MIN(source_language)
      ELSE 'zh'
    END AS merged_source_language,
    CASE
      WHEN BOOL_OR(status = 'processing') THEN 'processing'
      ELSE 'pending'
    END AS merged_status,
    COALESCE(
      ARRAY_AGG(DISTINCT target_language) FILTER (WHERE target_language IS NOT NULL),
      '{}'::text[]
    ) AS merged_target_languages,
    MAX(retry_count) AS merged_retry_count,
    (
      ARRAY_AGG(
        id
        ORDER BY
          CASE WHEN status = 'processing' THEN 0 ELSE 1 END,
          created_at ASC,
          id ASC
      )
    )[1] AS keep_id
  FROM translation_tasks
  WHERE status IN ('pending', 'processing')
  GROUP BY entity_type, entity_id
  HAVING COUNT(*) > 1
), merged_keep_rows AS (
  UPDATE translation_tasks tt
  SET
    hospital_type = grouped.merged_hospital_type,
    source_language = grouped.merged_source_language,
    target_language = CASE
      WHEN COALESCE(array_length(grouped.merged_target_languages, 1), 0) = 1
        THEN grouped.merged_target_languages[1]
      ELSE NULL
    END,
    target_languages = grouped.merged_target_languages,
    source_db = 'crm',
    status = grouped.merged_status,
    retry_count = grouped.merged_retry_count,
    error_message = NULL
  FROM grouped
  WHERE tt.id = grouped.keep_id
  RETURNING tt.id
)
DELETE FROM translation_tasks tt
USING grouped
WHERE tt.entity_type = grouped.entity_type
  AND tt.entity_id = grouped.entity_id
  AND tt.status IN ('pending', 'processing')
  AND tt.id <> grouped.keep_id;

-- Drop old unique constraint, add new partial unique index
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'translation_tasks'::regclass
      AND conname = 'translation_tasks_hospital_type_entity_type_entity_id_sourc_key'
  ) THEN
    ALTER TABLE translation_tasks
      DROP CONSTRAINT IF EXISTS translation_tasks_hospital_type_entity_type_entity_id_sourc_key;
  ELSE
    DROP INDEX IF EXISTS translation_tasks_hospital_type_entity_type_entity_id_sourc_key;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS translation_tasks_entity_dedup
  ON translation_tasks (source_db, entity_type, entity_id)
  WHERE status IN ('pending', 'processing');

-- Add translations jsonb to CRM tables
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE support_ticket_replies ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE consultations ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE question_collector_templates ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE question_collector_responses ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE chatbot_faq_items ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE chatbot_faq_categories ADD COLUMN IF NOT EXISTS translations JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Migration: 0025_translation_task_chunking.sql
-- Normalize translation task identity to one chunk + one target language.

ALTER TABLE translation_tasks
  ADD COLUMN IF NOT EXISTS chunk_key TEXT NOT NULL DEFAULT 'default';

-- Split any legacy multi-language rows so the
-- new queue shape is one row per single target language.
WITH legacy_backlog AS (
  SELECT
    id,
    source_db,
    hospital_type,
    entity_type,
    entity_id,
    chunk_key,
    source_language,
    status,
    error_message,
    retry_count,
    created_at,
    started_at,
    completed_at,
    fields_to_translate,
    detected_language,
    unnest(target_languages) AS target_language
  FROM translation_tasks
  WHERE COALESCE(array_length(target_languages, 1), 0) > 1
), split_rows AS (
  INSERT INTO translation_tasks (
    id,
    source_db,
    hospital_type,
    entity_type,
    entity_id,
    chunk_key,
    source_language,
    target_language,
    status,
    error_message,
    retry_count,
    created_at,
    started_at,
    completed_at,
    fields_to_translate,
    target_languages,
    detected_language
  )
  SELECT
    gen_random_uuid(),
    source_db,
    hospital_type,
    entity_type,
    entity_id,
    chunk_key,
    source_language,
    target_language,
    status,
    error_message,
    retry_count,
    created_at,
    started_at,
    completed_at,
    fields_to_translate,
    ARRAY[target_language]::text[],
    detected_language
  FROM legacy_backlog
  RETURNING id
)
DELETE FROM translation_tasks tt
USING legacy_backlog lb
WHERE tt.id = lb.id;

-- Backfill target_language so every task has a single language identity.
UPDATE translation_tasks
SET target_language = CASE
  WHEN COALESCE(array_length(target_languages, 1), 0) = 1 THEN target_languages[1]
  ELSE target_language
END
WHERE target_language IS NULL OR target_language = '';

ALTER TABLE translation_tasks
  ALTER COLUMN target_language SET NOT NULL;

-- Collapse duplicate identities across all statuses before creating the new unique index.
WITH ranked AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY source_db, entity_type, entity_id, chunk_key, target_language
      ORDER BY
        CASE status
          WHEN 'processing' THEN 0
          WHEN 'pending' THEN 1
          WHEN 'completed' THEN 2
          ELSE 3
        END,
        created_at DESC,
        id DESC
    ) AS rn
  FROM translation_tasks
)
DELETE FROM translation_tasks tt
USING ranked
WHERE tt.id = ranked.id
  AND ranked.rn > 1;

-- Drop the old entity-only dedupe index and replace it with the chunk-aware identity.
DROP INDEX IF EXISTS translation_tasks_entity_dedup;

CREATE UNIQUE INDEX IF NOT EXISTS translation_tasks_entity_dedup
  ON translation_tasks (source_db, entity_type, entity_id, chunk_key, target_language)

-- Migration: 002_create_message_tasks.sql
-- 002_create_message_tasks.sql
CREATE TABLE message_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  task_kind TEXT NOT NULL CHECK (task_kind IN ('TRANSLATE', 'SUMMARIZE')),
  target_language VARCHAR(10),
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  error_message TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX message_tasks_pending_idx ON message_tasks(status) WHERE status = 'PENDING';
CREATE INDEX message_tasks_message_id_idx ON message_tasks(message_id);

-- Migration: 003_m0_case_realignment.sql
-- 003_m0_case_realignment.sql
-- Section 0: Add new case assignment/treatment model
-- This file runs INSIDE a transaction (safe rollback on failure)

-- New enums
CREATE TYPE "CaseAssignmentStatus" AS ENUM ('UNASSIGNED', 'ASSIGNED');
CREATE TYPE "CaseTreatmentStage" AS ENUM ('CONFIRMED', 'IN_TREATMENT', 'POST_TREATMENT', 'COMPLETED', 'FOLLOW_UP');

-- Add new columns to cases
ALTER TABLE cases ADD COLUMN assignment_status "CaseAssignmentStatus" NOT NULL DEFAULT 'UNASSIGNED';
ALTER TABLE cases ADD COLUMN treatment_stage "CaseTreatmentStage";
ALTER TABLE cases ADD COLUMN condition_summary TEXT;
ALTER TABLE cases ADD COLUMN structured_data JSONB;
ALTER TABLE cases ADD COLUMN risk_flags TEXT[];
ALTER TABLE cases ADD COLUMN priority VARCHAR(20);
ALTER TABLE cases ADD COLUMN last_event_at TIMESTAMPTZ;
ALTER TABLE cases ADD COLUMN ai_summary_status "AISummaryStatus" NOT NULL DEFAULT 'PENDING';
ALTER TABLE cases ADD COLUMN question_collector_template_id UUID;

-- Backfill: map old status/stage → new assignment_status/treatment_stage
UPDATE cases SET assignment_status = 'ASSIGNED' WHERE assigned_hospital_id IS NOT NULL;
UPDATE cases SET treatment_stage = 'CONFIRMED' WHERE stage = 'HOSPITAL_CONTACTED' AND assigned_hospital_id IS NOT NULL;
UPDATE cases SET treatment_stage = 'IN_TREATMENT' WHERE stage = 'IN_TREATMENT';
UPDATE cases SET treatment_stage = 'COMPLETED' WHERE stage = 'TREATMENT_COMPLETED';

-- Migration: 003b_idempotency_keys.sql
-- Idempotency keys (Section 0.5.3)
CREATE TABLE IF NOT EXISTS idempotency_keys (
  key VARCHAR(255) PRIMARY KEY,
  operation VARCHAR(100) NOT NULL,
  result JSONB,               -- NULL while processing, set on completion
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TTL cleanup: add index for periodic purge
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_created ON idempotency_keys(created_at);

-- Migration: 003c_m0_indexes.sql
-- 003c_m0_indexes.sql
-- Runs OUTSIDE a transaction (migration runner detects CONCURRENTLY keyword).
-- IF NOT EXISTS makes each statement individually idempotent — safe partial re-run.

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cases_user_updated ON cases(patient_id, updated_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cases_assignment_stage_created ON cases(assignment_status, treatment_stage, created_at DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cases_assigned_hospital_created ON cases(assigned_hospital_id, created_at DESC) WHERE assigned_hospital_id IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cases_risk_flags_gin ON cases USING gin(risk_flags);

-- Migration: 004_m1_quotes_chc.sql
-- ============================================================================
-- Module 1: Quotes + CaseHospitalContacts
-- ============================================================================

-- Enums
CREATE TYPE "CHCSubStatus" AS ENUM ('DISTRIBUTED', 'NEED_INFO', 'QUOTED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'REMOVED');
CREATE TYPE "QuoteStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED');

-- case_hospital_contacts
CREATE TABLE case_hospital_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  sub_status "CHCSubStatus" NOT NULL DEFAULT 'DISTRIBUTED',
  selected_by_patient_at TIMESTAMPTZ,
  distributed_at TIMESTAMPTZ DEFAULT now(),
  first_reply_at TIMESTAMPTZ,
  quote_id UUID,
  patient_viewed_quote_at TIMESTAMPTZ,
  patient_accepted_at TIMESTAMPTZ,
  patient_rejected_at TIMESTAMPTZ,
  reminder_sent_at TIMESTAMPTZ,
  removed_at TIMESTAMPTZ,
  removed_reason TEXT,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(case_id, hospital_id)
);

-- quotes
CREATE TABLE quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  quote_number VARCHAR(50) NOT NULL UNIQUE,
  version INT NOT NULL DEFAULT 1,
  status "QuoteStatus" NOT NULL DEFAULT 'PENDING',
  is_draft BOOLEAN NOT NULL DEFAULT true,
  total_amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  valid_until TIMESTAMPTZ NOT NULL,
  treatment_plan TEXT,
  line_items JSONB,
  notes TEXT,
  sent_at TIMESTAMPTZ,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Deferred FK: CHC → quotes
ALTER TABLE case_hospital_contacts
  ADD CONSTRAINT chc_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id);

-- Indexes
CREATE INDEX idx_chc_hospital_sub_distributed ON case_hospital_contacts(hospital_id, sub_status, distributed_at DESC);
CREATE INDEX idx_chc_case_sub ON case_hospital_contacts(case_id, sub_status);
CREATE INDEX idx_chc_sub_distributed ON case_hospital_contacts(sub_status, distributed_at);
CREATE INDEX idx_chc_quote_id ON case_hospital_contacts(quote_id) WHERE quote_id IS NOT NULL;
CREATE INDEX idx_quotes_case_status_created ON quotes(case_id, status, created_at DESC);
CREATE INDEX idx_quotes_hospital_status_created ON quotes(hospital_id, status, created_at DESC);
CREATE INDEX idx_quotes_valid_until_active ON quotes(valid_until) WHERE status = 'PENDING';

-- Migration: 005_m2_events.sql
-- Module 2: Events / Timeline

CREATE TYPE "CaseEventType" AS ENUM (
  'CASE_CREATED', 'CASE_DISTRIBUTED', 'CASE_ASSIGNED', 'CASE_STATUS_CHANGED', 'CASE_STAGE_ADVANCED',
  'HOSPITALS_SELECTED', 'HOSPITAL_REPLIED', 'HOSPITAL_NEED_INFO', 'HOSPITAL_REMOVED',
  'QUOTE_SENT', 'QUOTE_ACCEPTED', 'QUOTE_REJECTED', 'QUOTE_EXPIRED', 'QUOTE_RESENT',
  'MESSAGE_SENT', 'MESSAGE_RECEIVED',
  'QUESTIONNAIRE_SUBMITTED', 'CONSULTATION_SCHEDULED', 'CONSULTATION_COMPLETED',
  'DOCUMENT_UPLOADED',
  'ORDER_PLACED', 'ORDER_STATUS_CHANGED',
  'MILESTONE_ADDED', 'MILESTONE_UPDATED', 'JOURNEY_UPDATED',
  'TICKET_CREATED', 'TICKET_RESOLVED',
  'AI_SUMMARY_GENERATED'
);

CREATE TYPE "ActorType" AS ENUM ('PATIENT', 'HOSPITAL', 'ADMIN', 'SYSTEM');

CREATE TABLE case_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  event_type "CaseEventType" NOT NULL,
  actor_type "ActorType" NOT NULL,
  actor_id UUID,
  event_data JSONB,
  is_visible_to_patient BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_case_events_case_created ON case_events(case_id, created_at DESC);
CREATE INDEX idx_case_events_type ON case_events(event_type, created_at DESC);

-- Migration: 006_m3_tickets.sql
-- Module 3: Support Tickets

CREATE TYPE "TicketType" AS ENUM ('ACCOUNT_ISSUES', 'PAYMENT_PROBLEMS', 'HOSPITAL_COMMUNICATION', 'DOCUMENT_HELP', 'VISA_TRAVEL', 'GENERAL_QUESTIONS', 'FEEDBACK');
CREATE TYPE "TicketPriority" AS ENUM ('HIGH', 'MEDIUM', 'LOW');
CREATE TYPE "TicketStatus" AS ENUM ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_INFO', 'RESOLVED', 'CLOSED');
CREATE TYPE "TicketReplyRole" AS ENUM ('ADMIN', 'PATIENT');

CREATE TABLE support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number VARCHAR(50) NOT NULL UNIQUE,
  patient_id UUID NOT NULL REFERENCES users(id),
  case_id UUID REFERENCES cases(id),
  type "TicketType" NOT NULL,
  priority "TicketPriority" NOT NULL DEFAULT 'MEDIUM',
  status "TicketStatus" NOT NULL DEFAULT 'OPEN',
  subject VARCHAR(500),
  description TEXT NOT NULL,
  source_page VARCHAR(200),
  assigned_to UUID REFERENCES users(id),
  sla_deadline TIMESTAMPTZ,
  resolution_note TEXT,
  resolved_at TIMESTAMPTZ,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE support_ticket_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES users(id),
  author_role "TicketReplyRole" NOT NULL,
  content TEXT NOT NULL,
  is_internal_note BOOLEAN NOT NULL DEFAULT false,
  attachments JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tickets_patient_status ON support_tickets(patient_id, status, created_at DESC);
CREATE INDEX idx_tickets_queue ON support_tickets(status, priority, sla_deadline ASC NULLS LAST, created_at DESC);
CREATE INDEX idx_ticket_replies_ticket ON support_ticket_replies(ticket_id, created_at DESC);
CREATE INDEX idx_tickets_assigned_status ON support_tickets(assigned_to, status) WHERE assigned_to IS NOT NULL;

-- Migration: 007_m4_orders_packages.sql
-- Migration 007: Module 4 — Orders + Packages
-- Adds packages and orders tables with supporting enums and indexes.

-- Enums
CREATE TYPE "PackageType" AS ENUM ('CONSULTATION', 'HEALTH_CHECKUP', 'SECOND_OPINION', 'VISA_PACKAGE', 'INSURANCE', 'ACCOMMODATION', 'TREATMENT_DEPOSIT', 'TRANSLATION');
CREATE TYPE "PackageStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "OrderType" AS ENUM ('CONSULTATION', 'HEALTH_CHECKUP', 'SECOND_OPINION', 'VISA_PACKAGE', 'INSURANCE', 'ACCOMMODATION', 'TREATMENT_DEPOSIT', 'TRANSLATION');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING_PAYMENT', 'PAID', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REFUNDED');

-- packages table
CREATE TABLE packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name_en VARCHAR(200) NOT NULL,
  name_zh VARCHAR(200),
  type "PackageType" NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  description_en TEXT,
  description_zh TEXT,
  inclusions JSONB,
  cover_image_url VARCHAR(500),
  sort_weight INT DEFAULT 0,
  status "PackageStatus" NOT NULL DEFAULT 'DRAFT',
  publish_at TIMESTAMPTZ,
  takedown_at TIMESTAMPTZ,
  config JSONB,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- orders table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(50) NOT NULL UNIQUE,
  patient_id UUID NOT NULL REFERENCES users(id),
  case_id UUID REFERENCES cases(id),
  package_id UUID REFERENCES packages(id),
  type "OrderType" NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  status "OrderStatus" NOT NULL DEFAULT 'PENDING_PAYMENT',
  payment_method VARCHAR(50),
  paid_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  refunded_amount DECIMAL(12,2),
  refund_reason TEXT,
  metadata JSONB,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_packages_status_type ON packages(status, type, publish_at DESC NULLS LAST);
CREATE INDEX idx_packages_created_by_status ON packages(created_by, status, created_at DESC);
CREATE INDEX idx_orders_patient_status ON orders(patient_id, status, created_at DESC);
CREATE INDEX idx_orders_status_type ON orders(status, type, created_at DESC);
CREATE INDEX idx_orders_case_created ON orders(case_id, created_at DESC) WHERE case_id IS NOT NULL;

-- Migration: 008_m5_journey.sql
-- Module 5: Journey + Milestones
-- Enum
CREATE TYPE "MilestoneEventType" AS ENUM (
  'FLIGHT_ARRIVAL', 'FLIGHT_DEPARTURE',
  'HOTEL_CHECKIN', 'HOTEL_CHECKOUT',
  'HOSPITAL_APPOINTMENT', 'PRE_OP_EXAM', 'SURGERY_DATE', 'POST_OP_CHECKUP',
  'MEDICATION_SCHEDULE', 'FOLLOW_UP_REMOTE',
  'VISA_APPLICATION', 'VISA_APPROVED',
  'INSURANCE_CONFIRMED',
  'CUSTOM'
);

-- case_journeys
CREATE TABLE case_journeys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL UNIQUE REFERENCES cases(id),
  visa JSONB,
  insurance JSONB,
  accommodation JSONB,
  transportation JSONB,
  post_care JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- journey_milestones
CREATE TABLE journey_milestones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  event_type "MilestoneEventType" NOT NULL,
  event_date TIMESTAMPTZ NOT NULL,
  note TEXT,
  is_visible_to_patient BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE UNIQUE INDEX idx_case_journeys_case ON case_journeys(case_id);
CREATE INDEX idx_milestones_case_date ON journey_milestones(case_id, event_date ASC);
CREATE INDEX idx_milestones_patient_visible ON journey_milestones(is_visible_to_patient, event_date ASC) WHERE is_visible_to_patient = true;

-- Migration: 009_m6_question_collector.sql
-- Module 6: QuestionCollector
-- Templates, Responses, Customizations

-- Enum
CREATE TYPE "QCCompletionStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');

-- Templates
CREATE TABLE question_collector_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_name VARCHAR(200) NOT NULL,
  category VARCHAR(100) NOT NULL,
  procedure_types TEXT[],
  questions JSONB NOT NULL,
  version INT NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Responses
CREATE TABLE question_collector_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  template_id UUID NOT NULL REFERENCES question_collector_templates(id),
  user_id UUID NOT NULL REFERENCES users(id),
  responses JSONB NOT NULL,
  extracted_data JSONB,
  risk_flags TEXT[],
  completion_status "QCCompletionStatus" NOT NULL DEFAULT 'NOT_STARTED',
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Customizations
CREATE TABLE question_collector_customizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id UUID NOT NULL REFERENCES question_collector_templates(id),
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  customized_questions JSONB NOT NULL,
  customized_by UUID REFERENCES users(id),
  customized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(template_id, hospital_id)
);

-- Indexes
CREATE INDEX idx_qcr_case ON question_collector_responses(case_id, submitted_at DESC);
CREATE INDEX idx_qcr_risk_flags ON question_collector_responses USING gin(risk_flags);
CREATE INDEX idx_qcc_template_hospital ON question_collector_customizations(template_id, hospital_id);
CREATE INDEX idx_qcr_completion_submitted ON question_collector_responses(completion_status, submitted_at DESC);
CREATE INDEX idx_qct_active ON question_collector_templates(is_active, category);

-- Migration: 010_m7_service_catalog.sql
-- Module 7: ServiceCatalog + QuoteTemplates
-- Enum
CREATE TYPE "ServiceCatalogCategory" AS ENUM (
  'COSMETIC_SURGERY', 'DENTAL', 'DERMATOLOGY', 'ORTHOPEDIC',
  'CARDIAC', 'OPHTHALMIC', 'FERTILITY', 'WEIGHT_LOSS',
  'HAIR_RESTORATION', 'WELLNESS', 'OTHER'
);

-- service_catalog_items
CREATE TABLE service_catalog_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  name_en VARCHAR(200) NOT NULL,
  name_zh VARCHAR(200),
  category "ServiceCatalogCategory" NOT NULL,
  price_min DECIMAL(12,2) NOT NULL,
  price_max DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  estimated_stay_days INT,
  estimated_recovery_days INT,
  inclusions JSONB,
  is_public BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- quote_templates
CREATE TABLE quote_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  name VARCHAR(200) NOT NULL,
  condition_category VARCHAR(100),
  line_items_template JSONB NOT NULL,
  default_valid_days INT NOT NULL DEFAULT 30,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_sci_hospital_active ON service_catalog_items(hospital_id, is_active, category);
CREATE INDEX idx_sci_hospital_public ON service_catalog_items(hospital_id, is_public) WHERE is_public = true;
CREATE INDEX idx_qt_hospital_active ON quote_templates(hospital_id, is_active);

-- Migration: 011_m9_booking.sql
-- Module 9: BookingRequest + Patient Auth
-- Enums
CREATE TYPE "BookingRequestStatus" AS ENUM ('PENDING', 'HOSPITALS_MATCHED', 'SELECTIONS_SAVED', 'COMPLETED', 'EXPIRED');
CREATE TYPE "BookingConditionType" AS ENUM ('COSMETIC', 'MEDICAL', 'DENTAL', 'WELLNESS', 'OTHER');

-- booking_requests
CREATE TABLE booking_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  request_number VARCHAR(50) NOT NULL UNIQUE,
  condition_type "BookingConditionType" NOT NULL,
  condition_category VARCHAR(100) NOT NULL,
  condition_description TEXT,
  destination_preference JSONB,
  preferred_language VARCHAR(10) NOT NULL DEFAULT 'en',
  status "BookingRequestStatus" NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- booking_request_hospitals
CREATE TABLE booking_request_hospitals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_request_id UUID NOT NULL REFERENCES booking_requests(id) ON DELETE CASCADE,
  hospital_id UUID NOT NULL REFERENCES hospitals(id),
  is_recommended BOOLEAN NOT NULL DEFAULT false,
  match_score INT,
  recommendation_reason TEXT,
  selected_by_patient BOOLEAN NOT NULL DEFAULT false,
  selected_at TIMESTAMPTZ,
  UNIQUE(booking_request_id, hospital_id)
);

-- Indexes
CREATE INDEX idx_booking_requests_user ON booking_requests(user_id, created_at DESC);
CREATE INDEX idx_booking_requests_status ON booking_requests(status, created_at DESC);
CREATE INDEX idx_booking_request_hospitals_br ON booking_request_hospitals(booking_request_id);

-- TODO: Add booking_request_id column to cases table in a future migration.
-- ALTER TABLE cases ADD COLUMN booking_request_id UUID REFERENCES booking_requests(id);
-- This is deferred because the cases table is managed by earlier migrations.

-- Migration: 012_add_city_to_hospitals.sql
ALTER TABLE hospitals ADD COLUMN city VARCHAR(200);

-- Migration: 013_align_admin_portal_enums.sql
-- Align enum values with admin portal CDE spec.
-- This migration intentionally removes legacy order/package enum members.

-- ---------------------------------------------------------------------------
-- PackageType
-- ---------------------------------------------------------------------------
ALTER TABLE packages
  ALTER COLUMN type DROP DEFAULT;

CREATE TYPE "PackageType_new" AS ENUM (
  'CONSULTATION',
  'HEALTH_CHECKUP',
  'SECOND_OPINION',
  'VISA_PACKAGE',
  'INSURANCE',
  'ACCOMMODATION',
  'TREATMENT_DEPOSIT',
  'TRANSLATION'
);

ALTER TABLE packages
  ALTER COLUMN type TYPE "PackageType_new"
  USING (
    CASE
      WHEN type::text = 'TREATMENT' THEN 'HEALTH_CHECKUP'
      WHEN type::text = 'BUNDLE' THEN 'CONSULTATION'
      WHEN type::text = 'ADD_ON' THEN 'TRANSLATION'
      ELSE type::text
    END::"PackageType_new"
  );

DROP TYPE "PackageType";
ALTER TYPE "PackageType_new" RENAME TO "PackageType";

-- ---------------------------------------------------------------------------
-- OrderType
-- ---------------------------------------------------------------------------
ALTER TABLE orders
  ALTER COLUMN type DROP DEFAULT;

CREATE TYPE "OrderType_new" AS ENUM (
  'CONSULTATION',
  'HEALTH_CHECKUP',
  'SECOND_OPINION',
  'VISA_PACKAGE',
  'INSURANCE',
  'ACCOMMODATION',
  'TREATMENT_DEPOSIT',
  'TRANSLATION'
);

ALTER TABLE orders
  ALTER COLUMN type TYPE "OrderType_new"
  USING (
    CASE
      WHEN type::text = 'PACKAGE' THEN 'CONSULTATION'
      WHEN type::text = 'CUSTOM' THEN 'TRANSLATION'
      ELSE type::text
    END::"OrderType_new"
  );

DROP TYPE "OrderType";
ALTER TYPE "OrderType_new" RENAME TO "OrderType";

-- ---------------------------------------------------------------------------
-- TicketStatus (adds IN_PROGRESS)
-- ---------------------------------------------------------------------------
ALTER TABLE support_tickets
  ALTER COLUMN status DROP DEFAULT;

CREATE TYPE "TicketStatus_new" AS ENUM (
  'OPEN',
  'ASSIGNED',
  'IN_PROGRESS',
  'PENDING_INFO',
  'RESOLVED',
  'CLOSED'
);

ALTER TABLE support_tickets
  ALTER COLUMN status TYPE "TicketStatus_new"
  USING (status::text::"TicketStatus_new");

DROP TYPE "TicketStatus";
ALTER TYPE "TicketStatus_new" RENAME TO "TicketStatus";

ALTER TABLE support_tickets
  ALTER COLUMN status SET DEFAULT 'OPEN';

-- Migration: 014_chatbot_faq_items.sql
CREATE TABLE chatbot_faq_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category VARCHAR(100) NOT NULL,
  question_en TEXT NOT NULL,
  question_zh TEXT NOT NULL,
  answer_en TEXT NOT NULL,
  answer_zh TEXT NOT NULL,
  keywords JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX chatbot_faq_items_category_idx ON chatbot_faq_items(category);
CREATE INDEX chatbot_faq_items_is_active_idx ON chatbot_faq_items(is_active);

-- Migration: 015_patient_auth_columns.sql
-- Ensure patient-auth columns exist on users table.
-- This is safe to run on both old and new databases.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);

-- Migration: 016_notification_settings.sql
-- Add notification_settings JSONB column to users table.
-- Stores per-user notification preferences.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS notification_settings JSONB;

-- Migration: 017_chatbot_faq_single_language_and_hospital_type.sql
-- Refactor chatbot FAQ data model:
-- 1) Move from multilingual question/answer fields to single-language fields.
-- 2) Add hospital_type scope (REGULAR / COSMETIC).

ALTER TABLE chatbot_faq_items
  ADD COLUMN IF NOT EXISTS hospital_type VARCHAR(20) NOT NULL DEFAULT 'REGULAR';

ALTER TABLE chatbot_faq_items
  ADD COLUMN IF NOT EXISTS question TEXT;

ALTER TABLE chatbot_faq_items
  ADD COLUMN IF NOT EXISTS answer TEXT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'chatbot_faq_items'
      AND column_name IN ('question_en', 'question_zh', 'answer_en', 'answer_zh')
  ) THEN
    UPDATE chatbot_faq_items
    SET
      question = COALESCE(question, NULLIF(question_en, ''), NULLIF(question_zh, ''), ''),
      answer = COALESCE(answer, NULLIF(answer_en, ''), NULLIF(answer_zh, ''), '');
  END IF;
END $$;

ALTER TABLE chatbot_faq_items
  ALTER COLUMN question SET NOT NULL;

ALTER TABLE chatbot_faq_items
  ALTER COLUMN answer SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chatbot_faq_items_hospital_type_check'
  ) THEN
    ALTER TABLE chatbot_faq_items
      ADD CONSTRAINT chatbot_faq_items_hospital_type_check
      CHECK (hospital_type IN ('REGULAR', 'COSMETIC'));
  END IF;
END $$;

ALTER TABLE chatbot_faq_items
  DROP COLUMN IF EXISTS question_en,
  DROP COLUMN IF EXISTS question_zh,
  DROP COLUMN IF EXISTS answer_en,
  DROP COLUMN IF EXISTS answer_zh;

CREATE INDEX IF NOT EXISTS chatbot_faq_items_hospital_type_idx
  ON chatbot_faq_items(hospital_type);

-- Migration: 018_hospital_portal_email_templates_and_faq_scope.sql
-- Hospital portal enhancements data prerequisites:
-- 1) Create email_templates table
-- 2) Add hospital_id scope to chatbot_faq_items

CREATE TABLE IF NOT EXISTS email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id UUID NOT NULL,
  name VARCHAR(200) NOT NULL,
  type VARCHAR(50) NOT NULL,
  subject VARCHAR(500) NOT NULL,
  body TEXT NOT NULL,
  variables JSONB DEFAULT '[]'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS email_templates_hospital_id_idx
  ON email_templates (hospital_id);
CREATE INDEX IF NOT EXISTS email_templates_type_idx
  ON email_templates (type);
CREATE INDEX IF NOT EXISTS email_templates_status_idx
  ON email_templates (status);

ALTER TABLE chatbot_faq_items
  ADD COLUMN IF NOT EXISTS hospital_id UUID;

CREATE INDEX IF NOT EXISTS chatbot_faq_items_hospital_id_idx
  ON chatbot_faq_items (hospital_id);

-- Migration: 019_chatbot_faq_categories.sql
CREATE TABLE IF NOT EXISTS chatbot_faq_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  hospital_type VARCHAR(20) NOT NULL,
  sort_order INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT chatbot_faq_categories_hospital_type_check
    CHECK (hospital_type IN ('REGULAR', 'COSMETIC')),
  CONSTRAINT chatbot_faq_categories_name_hospital_type_key
    UNIQUE (name, hospital_type)
);

CREATE INDEX IF NOT EXISTS chatbot_faq_categories_hospital_type_idx
  ON chatbot_faq_categories(hospital_type);
CREATE INDEX IF NOT EXISTS chatbot_faq_categories_is_active_idx
  ON chatbot_faq_categories(is_active);

INSERT INTO chatbot_faq_categories (name, hospital_type, sort_order, is_active, updated_at)
SELECT
  category AS name,
  hospital_type,
  MIN(sort_order) AS sort_order,
  BOOL_OR(is_active) AS is_active,
  CURRENT_TIMESTAMP AS updated_at
FROM chatbot_faq_items
WHERE NOT EXISTS (
  SELECT 1
  FROM chatbot_faq_categories existing
  WHERE existing.name = chatbot_faq_items.category
    AND existing.hospital_type = chatbot_faq_items.hospital_type
    AND existing.hospital_id IS NULL
)
GROUP BY category, hospital_type
;

-- Migration: 020_faq_attachments.sql
ALTER TABLE chatbot_faq_items ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]';

-- Migration: 021_users_keycloak_user_id.sql
-- Add keycloak_user_id to users for stable Keycloak -> CRM identity mapping.
-- Safe to run on databases that already have the column/index.
-- Backfill hospital users from hospital_registration_tokens when possible.
-- Admin users are NOT backfilled here because there is no DB-side source of truth.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS keycloak_user_id VARCHAR(100);

WITH latest_tokens AS (
  SELECT DISTINCT ON (email, hospital_id)
    email,
    hospital_id,
    keycloak_user_id
  FROM hospital_registration_tokens
  WHERE keycloak_user_id IS NOT NULL
  ORDER BY email, hospital_id, used_at DESC NULLS LAST
)
UPDATE users AS u
SET keycloak_user_id = lt.keycloak_user_id
FROM latest_tokens AS lt
WHERE u.role = 'HOSPITAL'
  AND u.keycloak_user_id IS NULL
  AND u.email = lt.email
  AND u.hospital_id IS NOT DISTINCT FROM lt.hospital_id;

CREATE UNIQUE INDEX IF NOT EXISTS users_keycloak_user_id_key
  ON users (keycloak_user_id)
  WHERE keycloak_user_id IS NOT NULL;

-- Migration: 022_email_template_attachments.sql
-- Add attachments column to email_templates for file/image uploads
ALTER TABLE email_templates
  ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]'::jsonb;

-- Migration: 023_faq_categories_hospital_id.sql
-- Add hospital_id to chatbot_faq_categories for per-hospital category management
ALTER TABLE chatbot_faq_categories
  ADD COLUMN IF NOT EXISTS hospital_id UUID;

CREATE INDEX IF NOT EXISTS chatbot_faq_categories_hospital_id_idx
  ON chatbot_faq_categories (hospital_id);

-- Drop old unique constraint (name, hospital_type) and recreate with hospital_id
ALTER TABLE chatbot_faq_categories
  DROP CONSTRAINT IF EXISTS chatbot_faq_categories_name_hospital_type_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'chatbot_faq_categories'::regclass
      AND conname = 'chatbot_faq_categories_name_hospital_type_hospital_id_key'
  ) THEN
    ALTER TABLE chatbot_faq_categories
      ADD CONSTRAINT chatbot_faq_categories_name_hospital_type_hospital_id_key
      UNIQUE (name, hospital_type, hospital_id);
  END IF;
END $$;

-- Migration: 024_dify_ai_chat.sql
DO $$
BEGIN
  ALTER TYPE "TicketType" ADD VALUE IF NOT EXISTS 'AI_ESCALATION';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS ai_chat_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id VARCHAR(255) NOT NULL,
  session_secret_hash VARCHAR(255),
  dify_conversation_id VARCHAR(255),
  patient_id UUID REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  hospital_type "HospitalType" NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ai_chat_sessions_session_id_key UNIQUE (session_id)
);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_session_id_idx
  ON ai_chat_sessions (session_id);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_dify_conversation_id_idx
  ON ai_chat_sessions (dify_conversation_id);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_patient_id_idx
  ON ai_chat_sessions (patient_id);

CREATE TABLE IF NOT EXISTS ai_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  intent VARCHAR(20),
  risk_level VARCHAR(20),
  can_answer BOOLEAN,
  next_action VARCHAR(50),
  citations JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_chat_messages_session_id_idx
  ON ai_chat_messages (session_id, created_at DESC);

CREATE TABLE IF NOT EXISTS dify_document_mappings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type VARCHAR(50) NOT NULL,
  entity_key VARCHAR(255) NOT NULL,
  dify_dataset_id VARCHAR(255) NOT NULL,
  dify_document_id VARCHAR(255) NOT NULL,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT dify_document_mappings_entity_key_unique UNIQUE (entity_type, entity_key)
);

CREATE INDEX IF NOT EXISTS dify_document_mappings_dataset_doc_idx
  ON dify_document_mappings (dify_dataset_id, dify_document_id);

CREATE TABLE IF NOT EXISTS ai_sync_outbox (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type VARCHAR(50) NOT NULL,
  entity_key VARCHAR(255) NOT NULL,
  action VARCHAR(20) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_sync_outbox_pending_idx
  ON ai_sync_outbox (status, next_retry_at, created_at);

CREATE INDEX IF NOT EXISTS ai_sync_outbox_entity_idx
  ON ai_sync_outbox (entity_type, entity_key);

-- Migration: 025_ai_policy_engine.sql
ALTER TABLE ai_chat_sessions
  ADD COLUMN IF NOT EXISTS condition_status VARCHAR(20) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS form_status VARCHAR(20) NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS doc_upload_status VARCHAR(20) NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS recommendation_status VARCHAR(30) NOT NULL DEFAULT 'not_started',
  ADD COLUMN IF NOT EXISTS consultation_status VARCHAR(30) NOT NULL DEFAULT 'not_introduced',
  ADD COLUMN IF NOT EXISTS package_status VARCHAR(30) NOT NULL DEFAULT 'not_introduced',
  ADD COLUMN IF NOT EXISTS handoff_status VARCHAR(20) NOT NULL DEFAULT 'not_needed',
  ADD COLUMN IF NOT EXISTS lead_maturity VARCHAR(20) NOT NULL DEFAULT 'browsing',
  ADD COLUMN IF NOT EXISTS risk_level VARCHAR(20) NOT NULL DEFAULT 'low',
  ADD COLUMN IF NOT EXISTS trust_or_objection VARCHAR(30) NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS pending_offer_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS pending_offer_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS pending_question_type VARCHAR(50),
  ADD COLUMN IF NOT EXISTS pending_question_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_next_action VARCHAR(50),
  ADD COLUMN IF NOT EXISTS last_resolved_intent VARCHAR(80),
  ADD COLUMN IF NOT EXISTS conversation_summary TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_policy_decision_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_user_message_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_assistant_message_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ai_chat_sessions_handoff_status_idx
  ON ai_chat_sessions (handoff_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_lead_maturity_idx
  ON ai_chat_sessions (lead_maturity, updated_at DESC);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_risk_level_idx
  ON ai_chat_sessions (risk_level, updated_at DESC);

ALTER TABLE ai_chat_messages
  ALTER COLUMN intent TYPE VARCHAR(80);

ALTER TABLE ai_chat_messages
  ADD COLUMN IF NOT EXISTS resolved_intent VARCHAR(80),
  ADD COLUMN IF NOT EXISTS secondary_action VARCHAR(50),
  ADD COLUMN IF NOT EXISTS response_mode VARCHAR(40),
  ADD COLUMN IF NOT EXISTS reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS shortlist JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS writeback_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS tool_trace JSONB NOT NULL DEFAULT '[]'::jsonb;

UPDATE ai_chat_messages
SET
  intent = COALESCE(intent, resolved_intent),
  next_action = COALESCE(next_action, secondary_action)
WHERE intent IS NULL OR next_action IS NULL;

CREATE INDEX IF NOT EXISTS ai_chat_messages_next_action_idx
  ON ai_chat_messages (next_action);

CREATE INDEX IF NOT EXISTS ai_chat_messages_role_created_at_idx
  ON ai_chat_messages (role, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_user_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID REFERENCES users(id) ON DELETE SET NULL,
  anonymous_key VARCHAR(255),
  condition_or_goal TEXT,
  condition_category VARCHAR(50),
  preferred_destination JSONB NOT NULL DEFAULT '[]'::jsonb,
  preferred_language VARCHAR(20),
  budget_band VARCHAR(20),
  urgency_level VARCHAR(20),
  existing_reports_status VARCHAR(20) NOT NULL DEFAULT 'none',
  objection_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  lead_stage VARCHAR(20) NOT NULL DEFAULT 'browsing',
  next_best_action VARCHAR(50),
  memory_summary TEXT NOT NULL DEFAULT '',
  source_confidence_map JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ai_user_profiles_patient_id_key UNIQUE (patient_id),
  CONSTRAINT ai_user_profiles_anonymous_key_key UNIQUE (anonymous_key)
);

CREATE INDEX IF NOT EXISTS ai_user_profiles_lead_stage_idx
  ON ai_user_profiles (lead_stage);

CREATE INDEX IF NOT EXISTS ai_user_profiles_updated_at_idx
  ON ai_user_profiles (updated_at DESC);

CREATE TABLE IF NOT EXISTS ai_chat_timeline_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
  patient_id UUID REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(50) NOT NULL,
  summary TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor VARCHAR(20) NOT NULL,
  confidence NUMERIC(5, 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_chat_timeline_events_session_id_idx
  ON ai_chat_timeline_events (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ai_chat_timeline_events_event_type_idx
  ON ai_chat_timeline_events (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS ai_chat_timeline_events_patient_id_idx
  ON ai_chat_timeline_events (patient_id, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_followup_triggers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
  patient_id UUID REFERENCES users(id) ON DELETE SET NULL,
  trigger_type VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  due_at TIMESTAMPTZ NOT NULL,
  channel VARCHAR(20) NOT NULL DEFAULT 'crm_queue',
  reason TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ai_followup_triggers_status_due_at_idx
  ON ai_followup_triggers (status, due_at);

CREATE INDEX IF NOT EXISTS ai_followup_triggers_trigger_status_idx
  ON ai_followup_triggers (trigger_type, status);

CREATE INDEX IF NOT EXISTS ai_followup_triggers_patient_due_at_idx
  ON ai_followup_triggers (patient_id, due_at);

CREATE UNIQUE INDEX IF NOT EXISTS ai_followup_triggers_pending_unique_idx
  ON ai_followup_triggers (session_id, trigger_type)
  WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS ai_handoffs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES ai_chat_sessions(id) ON DELETE CASCADE,
  patient_id UUID REFERENCES users(id) ON DELETE SET NULL,
  support_ticket_id UUID REFERENCES support_tickets(id) ON DELETE SET NULL,
  handoff_type VARCHAR(40) NOT NULL,
  priority VARCHAR(20) NOT NULL,
  reason_code VARCHAR(60) NOT NULL,
  brief JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'requested',
  assigned_to UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ai_handoffs_status_priority_idx
  ON ai_handoffs (status, priority, created_at DESC);

CREATE INDEX IF NOT EXISTS ai_handoffs_handoff_type_idx
  ON ai_handoffs (handoff_type, created_at DESC);

CREATE INDEX IF NOT EXISTS ai_handoffs_patient_id_idx
  ON ai_handoffs (patient_id, created_at DESC);

-- Migration: 026_ai_policy_engagement_mode.sql
ALTER TABLE ai_chat_sessions
  ADD COLUMN IF NOT EXISTS engagement_mode VARCHAR(30) NOT NULL DEFAULT 'LIGHT_DISCOVERY',
  ADD COLUMN IF NOT EXISTS prequalification_reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS entered_deep_workflow_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS ai_chat_sessions_engagement_mode_idx
  ON ai_chat_sessions (engagement_mode, updated_at DESC);

-- Migration: 027_ai_policy_selected_hospital.sql
ALTER TABLE ai_chat_sessions
  ADD COLUMN IF NOT EXISTS selected_hospital_id UUID REFERENCES hospitals(id) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS ai_chat_sessions_selected_hospital_id_idx
  ON ai_chat_sessions (selected_hospital_id, updated_at DESC);

-- Migration: 028_backfill_regular_hospitals_from_china.sql
-- Backfill missing active approved China hospitals into CRM v2.hospitals
-- Generated on 2026-04-04 from China Supabase and CRM Supabase live data.
-- Scope: only China hospitals where is_active = true AND status = 'approved' AND CRM hospitals.id is missing.
-- Source active approved hospitals: 62
-- Existing overlapping CRM hospital ids: 2
-- Insert rows in this migration: 60
-- Notes:
--   * CRM hospitals.id reuses the original China hospital UUID.
--   * name uses zh.name first; name_en uses cleaned en.name first.
--   * description prefers zh.short_description because current en.short_description is often mixed-language/noisy.
--   * logo_url is intentionally left NULL; image migration can happen separately.
--   * specialties is derived from hospital_i18n.core_specialties when available, else [].

BEGIN;

INSERT INTO hospitals (
  id,
  name,
  name_en,
  address,
  city,
  phone,
  email,
  description,
  logo_url,
  specialties,
  status,
  created_at,
  updated_at,
  type
) VALUES
  ('958d8184-c678-46ae-aa75-49a8530d1dcc', '首都医科大学附属北京安贞医院', 'Beijing Anzhen Hospital, Capital Medical University', '北京市朝阳区安贞路2号', 'beijing', NULL, NULL, '首都医科大学附属北京安贞医院成立于1984年，位于北京，是一所三甲综合性医院，在心血管病中心（成人）, 结构性心脏病与瓣膜中心, 心律失常与电生理中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:30.119651+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('44188313-1d1b-4bb2-a68a-8742c0cfef0b', '首都医科大学附属北京朝阳医院', 'Beijing Chaoyang Hospital, Capital Medical University', '北京市朝阳区工人体育场南路8号', 'beijing', NULL, NULL, '首都医科大学附属北京朝阳医院成立于1958年，位于北京，是一所三甲综合性医院，在呼吸与危重症医学中心（含介入呼吸与睡眠医学）, 胸部肿瘤与胸外科微创中心, 心血管医学中心（胸痛中心/结构性心脏病）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:31.228542+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('f95317df-3eb1-4fc7-a61a-fa02a24d6b06', '首都医科大学附属北京友谊医院', 'Beijing Friendship Hospital, Capital Medical University', '北京市西城区永安路95号', 'beijing', NULL, NULL, '首都医科大学附属北京友谊医院成立于1952年，位于北京，是一所三甲综合性医院，在肝病与肝移植中心, 消化病与内镜中心, 胆胰疾病中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:30.880368+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('82da3b60-b99c-4ea6-938d-643ad3436e0b', '北京积水潭医院', 'Beijing Jishuitan Hospital', '北京市西城区新街口东街31号', 'beijing', NULL, NULL, '北京积水潭医院成立于待查证年，位于北京，是一所三甲综合性医院，在骨科创伤中心, 脊柱外科与畸形矫形中心, 关节置换与重建中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:31.593345+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7763bc1c-c50c-4544-bce6-3b6e88bfeab9', '首都医科大学附属北京天坛医院', 'Beijing Tiantan Hospital, Capital Medical University', '北京市丰台区南四环西路119号', 'beijing', NULL, NULL, '首都医科大学附属北京天坛医院成立于1956年，位于北京，是一所三甲综合性医院，在神经外科中心, 神经内科与卒中中心（综合卒中中心）, 脑血管病与神经介入中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:30.501566+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('86261feb-843c-4f92-98f8-1ee0b8c40d78', '中国医学科学院肿瘤医院（国家癌症中心）', 'Cancer Hospital, Chinese Academy of Medical Sciences (National Cancer Center, China)', '北京市朝阳区潘家园南里17号', 'beijing', NULL, NULL, '中国医学科学院肿瘤医院（国家癌症中心）成立于1958年，位于北京，是一所其他综合性医院，在胸部肿瘤中心（肺癌/胸膜肿瘤）, 消化道肿瘤中心（胃肠道/食管）, 肝胆胰肿瘤中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:31.958415+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('65559336-adc8-466e-944d-b32574002500', '北京协和医院', 'Peking Union Medical College Hospital', '北京市东城区帅府园1号', 'beijing', NULL, NULL, '北京协和医院成立于1921年，位于北京，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心（神经内外科与介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:28.63258+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('971450f2-451c-4375-9145-0fb2d6db8587', '北京大学第一医院', 'Peking University First Hospital', '北京市西城区西什库大街8号', 'beijing', NULL, NULL, '北京大学第一医院成立于1915年，位于北京，是一所三甲综合性医院，在泌尿外科与男科中心, 肾脏病与血液净化中心, 心血管医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:29.389866+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('0c736e6f-4485-442d-afec-bc185060e8e2', '北京大学人民医院', 'Peking University People''s Hospital', '北京市西城区西直门南大街11号', 'beijing', NULL, NULL, '北京大学人民医院成立于1918年，位于北京，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:29.033752+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('24ec797a-5355-4ee3-a8ff-8bb5552b1909', '北京大学第三医院', 'Peking University Third Hospital (PUH3)', '北京市海淀区花园北路49号', 'beijing', NULL, NULL, '北京大学第三医院成立于1958年，位于北京市，是一所三甲综合性医院，在骨科与运动医学中心, 生殖医学中心, 关节重建与骨肿瘤中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:29.767193+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('affb6479-54cb-47b5-8fe0-8674c5eeb967', '成都市第五人民医院', 'Chengdu Fifth People''s Hospital', '成都市金牛区一环路北一段33号', 'chengdu', NULL, NULL, '成都市第五人民医院成立于待查证年，位于成都，是一所其他综合性医院，在心血管医学中心, 肿瘤与精准医学中心, 神经医学与卒中中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:46.873542+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('fb591355-61cf-4335-b801-e5b739fd6402', '成都市第一人民医院', 'Chengdu First People''s Hospital', '成都市青羊区文翁路18号', 'chengdu', NULL, NULL, '成都市第一人民医院成立于待查证年，位于成都，是一所其他综合性医院，在心血管医学中心（胸痛中心）, 神经医学与卒中中心, 创伤与急诊医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:45.7207+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('8398d177-00a0-4244-bfcc-390218fae9bd', '成都市第二人民医院', 'Chengdu Second People''s Hospital', '成都市锦江区庆云南街10号', 'chengdu', NULL, NULL, '成都市第二人民医院成立于待查证年，位于成都，是一所其他综合性医院，在心血管医学中心, 肿瘤综合诊疗中心, 神经医学中心（脑卒中与功能神经外科）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:46.129209+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('e7364844-085c-400e-819a-c6fdc17ddf87', '成都市第七人民医院', 'Chengdu Seventh People''s Hospital', '成都市武侯区红牌楼北街2号', 'chengdu', NULL, NULL, '成都市第七人民医院成立于待查证年，位于成都，是一所其他综合性医院，在呼吸与胸部疾病中心, 胸外科与微创肺部手术中心, 心血管医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:47.217606+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('6f649f32-de36-4f61-8669-90e324b9c76f', '成都市第三人民医院', 'Chengdu Third People''s Hospital', '成都市青羊区青羊横街82号', 'chengdu', NULL, NULL, '成都市第三人民医院成立于待查证年，位于成都，是一所其他综合性医院，在心血管疾病中心, 脑卒中与神经医学中心, 肿瘤多学科诊疗（MDT）中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:46.49035+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('ec8d7002-48ef-43be-b305-11b22600272e', '成都市妇女儿童中心医院', 'Chengdu Women and Children''s Central Hospital', '成都市青羊区日月大道一段1619号', 'chengdu', NULL, NULL, '成都市妇女儿童中心医院成立于待查证年，位于成都，是一所其他综合性医院，在产科危重症与胎盘植入中心（PAS）, 胎儿医学与产前诊断中心, 新生儿医学中心（NICU）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:47.618003+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('90899bef-26a3-45bb-82dd-a684bae846c6', '成都市公共卫生临床医疗中心', 'Public Health Clinical Center of Chengdu', '成都市青羊区金坛路377号', 'chengdu', NULL, NULL, '成都市公共卫生临床医疗中心成立于待查证年，位于成都，是一所其他综合性医院，在传染病与肝病中心, 呼吸与重症医学（ARDS/ECMO）中心, HIV/AIDS 诊疗中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:47.971024+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('c0e22ee8-6b14-4aec-95ba-3eef2cc1c141', '四川省人民医院（四川省医学科学院）', 'Sichuan Provincial People''s Hospital (Sichuan Academy of Medical Sciences)', '成都市青羊区一环路西二段32号', 'chengdu', NULL, NULL, '四川省人民医院（四川省医学科学院）成立于待查证年，位于成都，是一所三甲综合性医院，在心血管病中心, 肿瘤医学中心, 神经医学中心（脑卒中与神经外科）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:45.374723+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('09c8678a-6452-44bc-a518-77b771b6bade', '四川大学华西医院', 'West China Hospital, Sichuan University', '成都市武侯区国学巷37号', 'chengdu', NULL, NULL, '四川大学华西医院成立于1892年，位于成都，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心（神经内外科/卒中中心）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:44.645602+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('5a8ec4d7-731f-43d4-a4ef-caecf2e1177b', '四川大学华西第二医院', 'West China Second University Hospital, Sichuan University', '成都市武侯区人民南路三段20号', 'chengdu', NULL, NULL, '四川大学华西第二医院成立于待查证年，位于成都，是一所三甲综合性医院，在胎儿医学与高危产科中心, 生殖医学中心（辅助生殖）, 妇科肿瘤与微创外科中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:45.01769+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('e035c4a4-2a80-410e-a868-0cb5db5f5574', '重庆医科大学附属儿童医院', 'Children''s Hospital of Chongqing Medical University', '重庆市渝中区中山二路136号', 'chongqing', NULL, NULL, '重庆医科大学附属儿童医院成立于待查证年，位于重庆，是一所三甲综合性医院，在先天性心脏病与儿童心血管中心, 儿童肿瘤与血液肿瘤中心, 神经医学与癫痫中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:50.811399+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('9a14f841-8acb-4a92-8bfe-eb80c449e290', '重庆市急救医疗中心（重庆大学附属中心医院）', 'Chongqing Emergency Medical Center', '重庆市渝中区上清寺路1号', 'chongqing', NULL, NULL, '重庆市急救医疗中心（重庆大学附属中心医院）成立于待查证年，位于重庆，是一所三甲综合性医院，在国家（区域）创伤救治中心, 急诊医学与危重症医学中心（ED/ICU）, 胸痛中心（心血管急救一体化）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:51.892652+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('b925b90a-431d-4303-bb62-8005c65f528f', '重庆市人民医院', 'Chongqing People''s Hospital', '重庆市九龙坡区科园一路2号', 'chongqing', NULL, NULL, '重庆市人民医院成立于待查证年，位于重庆，是一所其他综合性医院，在心血管医学中心, 肿瘤与放射治疗中心, 神经医学中心（脑卒中与癫痫亚中心）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:51.539298+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('d79a3e94-3eed-468e-9b7d-500b55d05264', '重庆三峡中心医院', 'Chongqing Three Gorges Central Hospital', '重庆市万州区太白路165号', 'chongqing', NULL, NULL, '重庆三峡中心医院成立于待查证年，位于重庆，是一所三甲综合性医院，在心血管医学中心（含胸痛中心）, 结构性心脏病介入与瓣膜中心, 肿瘤中心（放疗·化疗·MDT）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:51.168098+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('3abd2b41-e96e-4580-be38-941a23ba2250', '重庆大学附属肿瘤医院（重庆市肿瘤医院）', 'Chongqing University Cancer Hospital (Chongqing Cancer Hospital)', '重庆市沙坪坝区大学城中路55号', 'chongqing', NULL, NULL, '重庆大学附属肿瘤医院（重庆市肿瘤医院）成立于待查证年，位于重庆，是一所三甲综合性医院，在胸部肿瘤中心（肺癌/纵隔肿瘤）, 消化道肿瘤中心（食管/胃/结直肠）, 肝胆胰肿瘤中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:50.421105+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('16e85d00-5986-47c5-aed6-17ae1f9032f6', '陆军军医大学大坪医院', 'Daping Hospital, Army Medical University', '重庆市渝中区大坪长江二路10号', 'chongqing', NULL, NULL, '陆军军医大学大坪医院成立于待查证年，位于重庆市，是一所三甲综合性医院，在创伤医学中心（国家级创伤救治体系核心单位）, 烧伤与整形修复中心, 骨科与运动医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:50.045883+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('eb8f84a6-4ae0-4fcc-9c5c-196ff5912af4', '陆军军医大学西南医院（第一附属医院）', 'Southwest Hospital, Army Medical University (The First Affiliated Hospital)', '重庆市沙坪坝区新桥正街30号', 'chongqing', NULL, NULL, '陆军军医大学西南医院（第一附属医院）成立于待查证年，位于重庆，是一所三甲综合性医院，在烧伤与创面修复中心, 肝胆胰外科与移植中心, 心血管医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:49.276076+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('4d99b2fb-40e0-4b76-9704-bb7b1f33d0a3', '重庆医科大学附属第一医院', 'The First Affiliated Hospital of Chongqing Medical University', '重庆市渝中区袁家岗友谊路1号', 'chongqing', NULL, NULL, '重庆医科大学附属第一医院成立于待查证年，位于重庆，是一所三甲综合性医院，在心血管医学中心, 肿瘤综合诊疗中心, 神经医学中心（神经内外科/卒中中心）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:48.534416+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('49ffa70a-b9c4-41ae-a75f-e34b46ddf2d2', '重庆医科大学附属第二医院', 'The Second Affiliated Hospital of Chongqing Medical University', '重庆市渝中区临江路76号', 'chongqing', NULL, NULL, '重庆医科大学附属第二医院成立于待查证年，位于重庆，是一所三甲综合性医院，在心血管医学中心, 肿瘤综合诊疗中心, 神经医学中心（脑卒中与功能神经）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:48.910023+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7b6cc193-630e-457e-af8d-875ab9bd77d2', '陆军军医大学新桥医院（第三军医大学第二附属医院）', 'Xinqiao Hospital, Army Medical University', '重庆市沙坪坝区新桥正街183号', 'chongqing', NULL, NULL, '陆军军医大学新桥医院（第三军医大学第二附属医院）成立于待查证年，位于重庆市，是一所三甲综合性医院，在心血管医学中心, 肿瘤诊疗中心, 神经医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:49.668295+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('6b631d8d-0b36-4ecb-818a-84e1c17367ea', '广东省中医院（广州中医药大学第一附属医院）', 'Guangdong Provincial Hospital of Traditional Chinese Medicine (The First Affiliated Hospital of Guangzhou University of Chinese Medicine)', '广州市越秀区大德路111号', 'guangzhou', NULL, NULL, '广东省中医院（广州中医药大学第一附属医院）成立于1933年，位于广州，是一所三甲综合性医院，在中西医结合肿瘤中心, 心血管疾病中心, 脑病与卒中中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:40.158604+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('f86ad4e6-47dc-42cb-bb26-4ae1833618df', '广东省人民医院', 'Guangdong Provincial People''s Hospital (Guangdong Academy of Medical Sciences)', '广州市越秀区中山二路106号', 'guangzhou', NULL, NULL, '广东省人民医院成立于1946年，位于广州，是一所三甲综合性医院，在心血管医学中心, 神经医学与卒中中心, 肿瘤医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:38.624037+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('90985ac5-de4d-424e-8ba2-10d5d9be2cb3', '南方医科大学南方医院', 'Nanfang Hospital, Southern Medical University', '广州市白云区广州大道北1838号', 'guangzhou', NULL, NULL, '南方医科大学南方医院成立于待查证年，位于广州，是一所三甲综合性医院，在心血管医学中心, 肿瘤综合诊疗中心, 神经医学中心（神经内外科+介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:37.896787+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7ec7af7e-2cde-4686-abe0-01347a93a213', '中山大学孙逸仙纪念医院', 'Sun Yat-sen Memorial Hospital, Sun Yat-sen University', '广州市越秀区沿江西路107号', 'guangzhou', NULL, NULL, '中山大学孙逸仙纪念医院成立于1835年，位于广州，是一所三甲综合性医院，在心血管医学中心, 肿瘤与乳腺疾病中心, 神经医学中心（神经内外科）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:37.164295+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('4944a7b3-acc8-45a6-80a0-6ee210cb8a86', '中山大学肿瘤防治中心（中山大学附属肿瘤医院）', 'Sun Yat-sen University Cancer Center', '广州市越秀区东风东路651号', 'guangzhou', NULL, NULL, '中山大学肿瘤防治中心（中山大学附属肿瘤医院）成立于1964年，位于广州，是一所三甲综合性医院，在胸部肿瘤中心（肺癌/食管癌）, 乳腺肿瘤中心, 胃肠与结直肠肿瘤中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:39.767661+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('812ca547-815a-4596-8583-8f377d32f0e2', '广州医科大学附属第一医院', 'The First Affiliated Hospital of Guangzhou Medical University', '广州市越秀区沿江西路151号', 'guangzhou', NULL, NULL, '广州医科大学附属第一医院成立于待查证年，位于广州，是一所三甲综合性医院，在国家呼吸医学中心/呼吸与危重症医学中心, 胸部肿瘤与胸外科中心, 心血管与结构性心脏病中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:38.968935+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('55e9264d-eafc-46ed-b6c0-cb74187f10ec', '中山大学附属第一医院', 'The First Affiliated Hospital of Sun Yat-sen University (FAHSYSU)', '广州市越秀区中山二路58号', 'guangzhou', NULL, NULL, '中山大学附属第一医院成立于1910年，位于广州，是一所三甲综合性医院，在心血管医学中心, 肿瘤综合诊疗中心, 神经医学中心（神经内外科/卒中中心）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:36.764251+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('8432110a-0903-4ca3-a8c2-6e272be36480', '广州医科大学附属第二医院', 'The Second Affiliated Hospital of Guangzhou Medical University', '广州市海珠区昌岗东路250号', 'guangzhou', NULL, NULL, '广州医科大学附属第二医院成立于待查证年，位于广州，是一所三甲综合性医院，在心血管医学中心（结构性心脏病与介入）, 肿瘤综合诊疗中心（MDT）, 神经医学中心（卒中与神外）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:39.37198+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('db39fd85-8e21-4805-94af-cc1977fcd2de', '中山大学附属第三医院', 'The Third Affiliated Hospital of Sun Yat-sen University (SYSU Third Hospital)', '广州市天河区天河路600号', 'guangzhou', NULL, NULL, '中山大学附属第三医院成立于1971年，位于广州，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心（MDT）, 神经医学与卒中中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:37.559271+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('a04fc727-def7-4999-95d2-0a1e6a792b1b', '南方医科大学珠江医院', 'Zhujiang Hospital of Southern Medical University', '广州市海珠区工业大道中253号', 'guangzhou', NULL, NULL, '南方医科大学珠江医院成立于待查证年，位于广州，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:38.250018+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('500fd231-bd61-4768-bee2-23c11a65095a', '复旦大学附属眼耳鼻喉科医院', 'Eye & ENT Hospital of Fudan University', '上海市徐汇区汾阳路83号', 'shanghai', NULL, NULL, '复旦大学附属眼耳鼻喉科医院成立于1952年，位于上海，是一所三甲综合性医院，在白内障与屈光手术中心, 角膜与眼表疾病中心, 青光眼中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:36.131448+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('71d088b9-148b-43d0-b841-466e9a2481f3', '复旦大学附属华山医院', 'Huashan Hospital, Fudan University', '上海市静安区乌鲁木齐中路12号', 'shanghai', NULL, NULL, '复旦大学附属华山医院成立于1907年，位于上海，是一所三甲综合性医院，在神经医学中心（神经外科/神经内科/神经重症）, 脑血管与卒中中心, 功能神经外科与神经调控中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:33.491042+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('4767f0e7-ae7e-470a-aefc-5436f4510801', '上海交通大学医学院附属仁济医院（东院）', 'Renji Hospital, School of Medicine, Shanghai Jiao Tong University (East Campus)', '上海市浦东新区浦建路160号', 'shanghai', NULL, NULL, '上海交通大学医学院附属仁济医院（东院）成立于1844年，位于上海，是一所三甲综合性医院，在消化病与内镜中心, 肝胆胰外科与肝移植中心, 泌尿外科与肾移植中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:33.848457+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('73552190-1233-4a28-b797-ffd09131ee5d', '上海交通大学医学院附属瑞金医院', 'Ruijin Hospital, Shanghai Jiao Tong University School of Medicine', '上海市黄浦区瑞金二路197号', 'shanghai', NULL, NULL, '上海交通大学医学院附属瑞金医院成立于1907年，位于上海，是一所三甲综合性医院，在国家代谢性疾病临床医学研究中心（内分泌与代谢中心）, 血液肿瘤与造血中心（上海血液学研究所联合）, 精准医学与医学基因组中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:33.138528+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('a172163d-0e68-4455-94e2-9b39d7fcdb40', '上海市胸科医院', 'Shanghai Chest Hospital, Shanghai Jiao Tong University', '上海市徐汇区淮海西路241号', 'shanghai', NULL, NULL, '上海市胸科医院成立于1957年，位于上海，是一所三甲综合性医院，在心血管中心（心外科+心内科）, 结构性心脏病与瓣膜介入中心, 胸外科与胸部肿瘤中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:35.778088+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7c763037-2c63-45d4-9d8e-99957bd4eca6', '上海交通大学医学院附属第一人民医院（上海市第一人民医院）', 'Shanghai General Hospital (Shanghai First People''s Hospital), SJTU School of Medicine', '上海市虹口区武进路100号', 'shanghai', NULL, NULL, '上海交通大学医学院附属第一人民医院（上海市第一人民医院）成立于1864年，位于上海，是一所三甲综合性医院，在心血管医学中心, 肿瘤综合诊疗中心（MDT）, 神经医学中心（卒中与神外）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:34.254444+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('58bc5990-61a8-47c7-83fe-7d30ef1779ee', '上海交通大学医学院附属第六人民医院（上海市第六人民医院）', 'Shanghai Sixth People''s Hospital, Shanghai Jiao Tong University School of Medicine', '上海市徐汇区宜山路600号', 'shanghai', NULL, NULL, '上海交通大学医学院附属第六人民医院（上海市第六人民医院）成立于1904年，位于上海，是一所三甲综合性医院，在创伤与骨科中心, 运动医学与关节镜中心, 足踝外科中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:34.628953+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('258197cf-f8ca-4d1e-aa42-3c307bfd28c1', '上海市第十人民医院（同济大学附属第十人民医院）', 'Shanghai Tenth People''s Hospital, Tongji University School of Medicine', '上海市静安区延长中路301号', 'shanghai', NULL, NULL, '上海市第十人民医院（同济大学附属第十人民医院）成立于待查证年，位于上海，是一所三甲综合性医院，在骨科与运动医学中心, 手外科与显微重建中心, 泌尿外科与微创结石中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:35.400794+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7c160f2c-3d60-4cc2-a014-9b9e3e19358a', '上海交通大学医学院附属新华医院', 'Xinhua Hospital, Shanghai Jiao Tong University School of Medicine', '上海市杨浦区控江路1665号', 'shanghai', NULL, NULL, '上海交通大学医学院附属新华医院成立于1958年，位于上海，是一所三甲综合性医院，在儿童消化与营养中心, 小儿外科与先天畸形修复中心, 先天性心脏病与小儿心血管中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:35.055752+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('7ebbd4e8-9b4a-4ed3-bf00-8e589d743814', '复旦大学附属中山医院', 'Zhongshan Hospital, Fudan University', '上海市徐汇区医学院路160号', 'shanghai', NULL, NULL, '复旦大学附属中山医院成立于1937年，位于上海，是一所三甲综合性医院，在心血管医学中心, 肝癌与肝胆胰外科中心（复旦大学肝癌研究所）, 器官移植中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:32.789848+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('94ed9220-721c-4f2f-b46e-0700cfebc31d', '深圳市宝安人民医院（集团）总院', 'Bao''an People''s Hospital (Group) General Hospital, Shenzhen', '深圳市宝安区新安二路118号', 'shenzhen', NULL, NULL, '深圳市宝安人民医院（集团）总院成立于待查证年，位于深圳，是一所三甲综合性医院，在心血管医学中心（心内/心外/介入一体化）, 肿瘤医学中心（放疗/化疗/介入/多学科MDT）, 神经医学中心（卒中与脑血管病）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:43.663984+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('24872781-f62f-49b5-8ff7-b97a78d6bc1d', '北京大学深圳医院', 'Peking University Shenzhen Hospital', '深圳市福田区莲花路1120号', 'shenzhen', NULL, NULL, '北京大学深圳医院成立于待查证年，位于深圳，是一所三甲综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心（脑卒中与神经介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:40.785654+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('936b079d-1c63-4098-8c03-8889b1ae9b8a', '深圳市儿童医院', 'Shenzhen Children''s Hospital', '深圳市福田区益田路7019号', 'shenzhen', NULL, NULL, '深圳市儿童医院成立于待查证年，位于深圳，是一所其他综合性医院，在先天性心脏病与心血管中心, 肿瘤与血液疾病中心, 神经医学与癫痫外科中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:42.559282+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('ade7f558-2456-4e70-8369-0404837b4144', '深圳市中医院', 'Shenzhen Hospital of Traditional Chinese Medicine', '深圳市福田区笋岗西路1号', 'shenzhen', NULL, NULL, '深圳市中医院成立于待查证年，位于深圳，是一所三甲综合性医院，在心血管疾病中西医结合中心, 肿瘤综合与精准医学中心, 神经医学与卒中中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:43.302121+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('54d2728a-cf57-4e6e-9c36-1178af0a6de1', '深圳市龙岗中心医院', 'Shenzhen Longgang Central Hospital', '深圳市龙岗区深惠路6082号', 'shenzhen', NULL, NULL, '深圳市龙岗中心医院成立于待查证年，位于深圳，是一所三甲综合性医院，在心血管与结构性心脏病中心, 肿瘤医学中心（放射治疗与MDT）, 神经医学中心（卒中与神经介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:44.060183+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('eb336882-37db-4c11-bd0d-1fb47d27ce89', '深圳市妇幼保健院', 'Shenzhen Maternity & Child Healthcare Hospital', '深圳市福田区福强路3012号', 'shenzhen', NULL, NULL, '深圳市妇幼保健院成立于待查证年，位于深圳，是一所其他综合性医院，在母胎医学与高危妊娠中心, 生殖医学中心（辅助生殖）, 新生儿医学与NICU中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:42.962248+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('e2af198c-d127-4407-a1ff-02d7d87c3ce9', '深圳市人民医院', 'Shenzhen People''s Hospital', '深圳市罗湖区东门北路1017号', 'shenzhen', NULL, NULL, '深圳市人民医院成立于1946年，位于深圳，是一所三甲综合性医院，在心血管医学中心, 肿瘤与放射治疗中心, 神经医学中心（脑卒中与神经外科）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:41.17337+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('88240cd7-f34a-4f09-8103-88f08f660024', '深圳市第二人民医院（深圳大学第一附属医院）', 'Shenzhen Second People''s Hospital (The First Affiliated Hospital of Shenzhen University)', '深圳市福田区笋岗西路3002号', 'shenzhen', NULL, NULL, '深圳市第二人民医院（深圳大学第一附属医院）成立于待查证年，位于深圳，是一所三甲综合性医院，在心血管病中心, 肿瘤医学中心, 神经医学中心（脑卒中与神经介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:41.52107+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('dac3297b-abb5-442a-875a-c159f9599908', '深圳市第三人民医院', 'The Third People''s Hospital of Shenzhen', '深圳市龙岗区布澜路29号', 'shenzhen', NULL, NULL, '深圳市第三人民医院成立于待查证年，位于深圳，是一所其他综合性医院，在感染性疾病国家临床研究中心（深圳）, 病毒性肝炎与肝病中心, HIV/AIDS 诊疗与随访管理中心等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:41.863308+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR'),
  ('cd012d91-f713-42dc-a8ad-ca1d35868b9f', '香港大学深圳医院', 'The University of Hong Kong–Shenzhen Hospital', '深圳市福田区海园一路1号', 'shenzhen', NULL, NULL, '香港大学深圳医院成立于2012年，位于深圳，是一所其他综合性医院，在心血管医学中心, 肿瘤医学中心, 神经医学中心（脑卒中与神经介入）等领域具有专业优势。', NULL, '[]'::jsonb, 'ACTIVE', '2025-09-16T23:49:42.22532+00:00', '2026-03-04T05:21:49.072217+00:00', 'REGULAR')
ON CONFLICT (id) DO NOTHING;

COMMIT;

-- Migration: 029_chatbot_state_truth_consolidation.sql
-- Destructive cleanup for fields retired by the chatbot truth-consolidation refactor.
-- Rollout requirement: deploy the CRM/API code that no longer reads these columns
-- to every running instance before applying this migration.

DROP INDEX IF EXISTS ai_chat_sessions_selected_hospital_id_idx;
DROP INDEX IF EXISTS ai_chat_sessions_lead_maturity_idx;

ALTER TABLE ai_chat_sessions
  DROP COLUMN IF EXISTS selected_hospital_id,
  DROP COLUMN IF EXISTS lead_maturity,
  DROP COLUMN IF EXISTS prequalification_reason_codes,
  DROP COLUMN IF EXISTS pending_offer_type,
  DROP COLUMN IF EXISTS pending_offer_payload,
  DROP COLUMN IF EXISTS pending_question_type,
  DROP COLUMN IF EXISTS pending_question_payload,
  DROP COLUMN IF EXISTS last_next_action,
  DROP COLUMN IF EXISTS last_resolved_intent;

-- Migration: 030_ai_chat_process_explained.sql
ALTER TABLE ai_chat_sessions
ADD COLUMN process_explained boolean NOT NULL DEFAULT false;

-- Migration: 031_ai_chat_canonical_truth_flags.sql
-- Rollout order for canonical chatbot truth flags:
-- 1. Deploy read paths that fall back to legacy status fields.
-- 2. Deploy write paths that set these booleans on deterministic actions.
-- 3. Backfill legacy sessions after step 2 if historical queries need explicit booleans.
-- 4. Remove fallback assumptions only after the backfill is stable in production.

ALTER TABLE ai_chat_sessions
  ADD COLUMN IF NOT EXISTS minimal_triage_complete BOOLEAN,
  ADD COLUMN IF NOT EXISTS recommendation_generated BOOLEAN,
  ADD COLUMN IF NOT EXISTS recommendation_selected BOOLEAN,
  ADD COLUMN IF NOT EXISTS consult_completed BOOLEAN,
  ADD COLUMN IF NOT EXISTS handoff_active BOOLEAN;

-- Migration: 031_patient_site_identity.sql
DO $$
BEGIN
  CREATE TYPE "PatientSite" AS ENUM ('beauty', 'china');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS patient_site "PatientSite";

ALTER TABLE ai_chat_sessions
  ADD COLUMN IF NOT EXISTS site "PatientSite";

UPDATE users
SET patient_site = 'china'
WHERE role = 'PATIENT'
  AND patient_site IS NULL;

UPDATE ai_chat_sessions
SET site = 'china'
WHERE site IS NULL;

ALTER TABLE ai_chat_sessions
  ALTER COLUMN site SET NOT NULL;

ALTER TABLE users
  DROP CONSTRAINT IF EXISTS users_patient_site_required;

ALTER TABLE users
  ADD CONSTRAINT users_patient_site_required
  CHECK (
    (role = 'PATIENT' AND patient_site IS NOT NULL)
    OR (role <> 'PATIENT' AND patient_site IS NULL)
  );

DROP INDEX IF EXISTS users_email_key;

CREATE UNIQUE INDEX IF NOT EXISTS users_patient_email_site_key
  ON users USING btree (email text_ops, patient_site)
  WHERE role = 'PATIENT';

CREATE UNIQUE INDEX IF NOT EXISTS users_non_patient_email_key
  ON users USING btree (email text_ops)
  WHERE role <> 'PATIENT';

CREATE INDEX IF NOT EXISTS users_patient_site_idx
  ON users USING btree (patient_site);

CREATE INDEX IF NOT EXISTS ai_chat_sessions_site_idx
  ON ai_chat_sessions USING btree (site);

CREATE OR REPLACE FUNCTION prevent_cross_role_user_email_duplicates()
RETURNS trigger AS $$
BEGIN
  IF NEW.role = 'PATIENT' THEN
    IF EXISTS (
      SELECT 1
      FROM users
      WHERE email = NEW.email
        AND role <> 'PATIENT'
        AND id <> NEW.id
    ) THEN
      RAISE EXCEPTION 'EMAIL_ROLE_CONFLICT';
    END IF;
  ELSE
    IF EXISTS (
      SELECT 1
      FROM users
      WHERE email = NEW.email
        AND role = 'PATIENT'
        AND id <> NEW.id
    ) THEN
      RAISE EXCEPTION 'EMAIL_ROLE_CONFLICT';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_prevent_cross_role_email_duplicates ON users;

CREATE TRIGGER users_prevent_cross_role_email_duplicates
BEFORE INSERT OR UPDATE OF email, role, patient_site
ON users
FOR EACH ROW
EXECUTE FUNCTION prevent_cross_role_user_email_duplicates();

-- Migration: 032_ai_chat_canonical_truth_flags_nullable.sql
ALTER TABLE ai_chat_sessions
  ALTER COLUMN minimal_triage_complete DROP NOT NULL,
  ALTER COLUMN minimal_triage_complete DROP DEFAULT,
  ALTER COLUMN recommendation_generated DROP NOT NULL,
  ALTER COLUMN recommendation_generated DROP DEFAULT,
  ALTER COLUMN recommendation_selected DROP NOT NULL,
  ALTER COLUMN recommendation_selected DROP DEFAULT,
  ALTER COLUMN consult_completed DROP NOT NULL,
  ALTER COLUMN consult_completed DROP DEFAULT,
  ALTER COLUMN handoff_active DROP NOT NULL,
  ALTER COLUMN handoff_active DROP DEFAULT;

-- Migration: 032_ai_chat_session_site_scope.sql
ALTER TABLE ai_chat_sessions
  DROP CONSTRAINT IF EXISTS ai_chat_sessions_session_id_key;

DROP INDEX IF EXISTS ai_chat_sessions_session_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS ai_chat_sessions_session_id_site_key
  ON ai_chat_sessions USING btree (session_id text_ops, site enum_ops);

-- Migration: 033_ai_chat_canonical_truth_flags_repair.sql
-- Repair rows created by an older 031 rollout that materialized canonical truth flags as FALSE.
-- This is safe and idempotent: it only upgrades rows to TRUE when legacy deterministic statuses
-- already prove the canonical truth and leaves all other rows unchanged.

UPDATE ai_chat_sessions
SET minimal_triage_complete = TRUE
WHERE minimal_triage_complete IS DISTINCT FROM TRUE
  AND (
    UPPER(COALESCE(form_status, '')) IN ('COMPLETED', 'SUBMITTED')
    OR UPPER(COALESCE(doc_upload_status, '')) IN ('COMPLETED', 'SUBMITTED', 'READY')
  );

UPDATE ai_chat_sessions
SET recommendation_selected = TRUE
WHERE recommendation_selected IS DISTINCT FROM TRUE
  AND (
    UPPER(COALESCE(recommendation_status, '')) IN ('CONFIRMED', 'ACCEPTED')
    OR UPPER(COALESCE(package_status, '')) IN ('CONFIRMED', 'ACCEPTED')
    OR UPPER(COALESCE(consultation_status, '')) IN ('SCHEDULED', 'BOOKED', 'COMPLETED')
  );

UPDATE ai_chat_sessions
SET recommendation_generated = TRUE
WHERE recommendation_generated IS DISTINCT FROM TRUE
  AND (
    UPPER(COALESCE(recommendation_status, '')) IN ('CONFIRMED', 'ACCEPTED')
    OR UPPER(COALESCE(package_status, '')) IN ('CONFIRMED', 'ACCEPTED')
    OR UPPER(COALESCE(consultation_status, '')) IN ('SCHEDULED', 'BOOKED', 'COMPLETED')
    OR (
      UPPER(COALESCE(recommendation_status, '')) <> ''
      AND UPPER(COALESCE(recommendation_status, '')) <> 'NOT_STARTED'
    )
    OR (
      UPPER(COALESCE(package_status, '')) <> ''
      AND UPPER(COALESCE(package_status, '')) NOT IN ('NOT_INTRODUCED', 'NOT_STARTED')
    )
  );

UPDATE ai_chat_sessions
SET consult_completed = TRUE
WHERE consult_completed IS DISTINCT FROM TRUE
  AND UPPER(COALESCE(consultation_status, '')) = 'COMPLETED';

UPDATE ai_chat_sessions
SET handoff_active = TRUE
WHERE handoff_active IS DISTINCT FROM TRUE
  AND UPPER(COALESCE(handoff_status, '')) IN ('REQUESTED', 'OPEN', 'IN_PROGRESS');

-- Migration: 034_message_sender_overrides.sql
ALTER TABLE messages
  ALTER COLUMN sender_id DROP NOT NULL;

ALTER TABLE messages
  ADD COLUMN sender_role_override varchar(20),
  ADD COLUMN sender_name_override varchar(255);

-- Track the current schema head so future pnpm db:migrate runs stay incremental.
CREATE TABLE IF NOT EXISTS _migrations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO _migrations (name)
VALUES
  ('001_ai_summary_columns.sql'),
  ('0024_unified_translation.sql'),
  ('0025_translation_task_chunking.sql'),
  ('002_create_message_tasks.sql'),
  ('003_m0_case_realignment.sql'),
  ('003b_idempotency_keys.sql'),
  ('003c_m0_indexes.sql'),
  ('004_m1_quotes_chc.sql'),
  ('005_m2_events.sql'),
  ('006_m3_tickets.sql'),
  ('007_m4_orders_packages.sql'),
  ('008_m5_journey.sql'),
  ('009_m6_question_collector.sql'),
  ('010_m7_service_catalog.sql'),
  ('011_m9_booking.sql'),
  ('012_add_city_to_hospitals.sql'),
  ('013_align_admin_portal_enums.sql'),
  ('014_chatbot_faq_items.sql'),
  ('015_patient_auth_columns.sql'),
  ('016_notification_settings.sql'),
  ('017_chatbot_faq_single_language_and_hospital_type.sql'),
  ('018_hospital_portal_email_templates_and_faq_scope.sql'),
  ('019_chatbot_faq_categories.sql'),
  ('020_faq_attachments.sql'),
  ('021_users_keycloak_user_id.sql'),
  ('022_email_template_attachments.sql'),
  ('023_faq_categories_hospital_id.sql'),
  ('024_dify_ai_chat.sql'),
  ('025_ai_policy_engine.sql'),
  ('026_ai_policy_engagement_mode.sql'),
  ('027_ai_policy_selected_hospital.sql'),
  ('028_backfill_regular_hospitals_from_china.sql'),
  ('029_chatbot_state_truth_consolidation.sql'),
  ('030_ai_chat_process_explained.sql'),
  ('031_ai_chat_canonical_truth_flags.sql'),
  ('031_patient_site_identity.sql'),
  ('032_ai_chat_canonical_truth_flags_nullable.sql'),
  ('032_ai_chat_session_site_scope.sql'),
  ('033_ai_chat_canonical_truth_flags_repair.sql'),
  ('034_message_sender_overrides.sql')
ON CONFLICT (name) DO NOTHING;
