-- Generated by scripts/export-video-staging-bootstrap.mjs
-- Video interpretation control-plane schema only; contains no business data.
-- Do not hand-edit this file.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Video staging support: video-staging-auth.sql
-- Minimal identity compatibility for the de-identified video staging API.
-- This file is intentionally outside database/migrations: production and the
-- full CRM bootstrap must never receive this synthetic operator.

DO $$
BEGIN
  CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'HOSPITAL', 'PATIENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email varchar(255),
  name varchar(100) NOT NULL,
  role "UserRole" NOT NULL DEFAULT 'PATIENT',
  hospital_id uuid,
  status varchar(20) NOT NULL DEFAULT 'active',
  last_login_at timestamp(6),
  created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  keycloak_user_id varchar(100)
);

-- A previously interrupted full-bootstrap attempt may have created the base
-- table before later identity migrations ran. Converge that harmless partial
-- state as well as a genuinely empty database.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email varchar(255),
  ADD COLUMN IF NOT EXISTS hospital_id uuid,
  ADD COLUMN IF NOT EXISTS last_login_at timestamp(6),
  ADD COLUMN IF NOT EXISTS updated_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS keycloak_user_id varchar(100);

CREATE UNIQUE INDEX IF NOT EXISTS users_keycloak_user_id_key
  ON users (keycloak_user_id)
  WHERE keycloak_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS video_staging_users_normalized_email_key
  ON users (lower(email))
  WHERE email IS NOT NULL;

-- The first successful login from the isolated staging Keycloak realm binds
-- keycloak_user_id through authMiddleware's email fallback. The reserved
-- invalid.example address is synthetic and must exist only in that realm.
INSERT INTO users (id, email, name, role, updated_at)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  'video-staging-admin@invalid.example',
  'Video Staging Operator',
  'ADMIN',
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    updated_at = CURRENT_TIMESTAMP;

-- Video staging migration: 050_video_consultations.sql
-- Canonical video consultation table required by the interpretation control
-- plane. Production received this table before SQL migration tracking covered
-- it; keep this idempotent migration so a fresh staging database can bootstrap
-- without copying production data.

CREATE TABLE IF NOT EXISTS video_consultations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid,
  patient_id uuid,
  room_name text NOT NULL,
  status text NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN (
    'PENDING_CONFIRMATION', 'SCHEDULED', 'IN_PROGRESS',
    'COMPLETED', 'CANCELLED', 'REJECTED'
  )),
  started_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer,
  created_by uuid,
  livekit_server_url text,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  scheduled_at timestamptz,
  title text,
  description text,
  host_identity text,
  timezone text DEFAULT 'UTC',
  doctor_id text,
  doctor_name text,
  duration_minutes integer NOT NULL DEFAULT 30,
  doctor_response_at timestamptz,
  doctor_response_note text,
  patient_name text,
  patient_email text,
  patient_language text DEFAULT 'en'
);

CREATE INDEX IF NOT EXISTS video_consultations_case_id_idx
  ON video_consultations (case_id);
CREATE INDEX IF NOT EXISTS video_consultations_doctor_id_idx
  ON video_consultations (doctor_id);
CREATE INDEX IF NOT EXISTS video_consultations_doctor_scheduled_at_idx
  ON video_consultations (doctor_id, scheduled_at);
CREATE INDEX IF NOT EXISTS video_consultations_patient_id_idx
  ON video_consultations (patient_id);
CREATE INDEX IF NOT EXISTS video_consultations_patient_scheduled_at_idx
  ON video_consultations (patient_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS video_consultations_room_name_idx
  ON video_consultations (room_name);
CREATE INDEX IF NOT EXISTS video_consultations_scheduled_at_idx
  ON video_consultations (scheduled_at);
CREATE INDEX IF NOT EXISTS video_consultations_status_idx
  ON video_consultations (status);

-- The video-only staging bootstrap intentionally does not require the wider
-- CRM schema. Add the production surgeon relationship when that table exists,
-- while keeping an otherwise empty de-identified evaluation database valid.
DO $$
BEGIN
  IF to_regclass('public.surgeons') IS NOT NULL THEN
    ALTER TABLE video_consultations
      ADD CONSTRAINT video_consultations_doctor_id_fkey
      FOREIGN KEY (doctor_id) REFERENCES surgeons(surgeon_id) ON DELETE SET NULL;
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Video staging migration: 051_video_interpretation_control_plane.sql
-- Low-cost hosted video interpretation control plane.
-- Content is intentionally absent: these tables contain authority, lifecycle,
-- and non-content metering only. Audio/captions/transcripts stay in memory.

ALTER TABLE video_consultations
  ADD COLUMN IF NOT EXISTS room_generation integer NOT NULL DEFAULT 1;

DO $$
BEGIN
  ALTER TABLE video_consultations
    ADD CONSTRAINT video_consultations_room_generation_positive CHECK (room_generation > 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS video_consultation_hosted_deployments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  deployment_name text NOT NULL UNIQUE,
  bootstrap_secret_digest text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  rotated_at timestamptz,
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS video_consultation_ai_consents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES video_consultations(id) ON DELETE CASCADE,
  participant_identity text NOT NULL,
  policy_version text NOT NULL,
  state text NOT NULL CHECK (state IN ('GRANTED', 'DECLINED', 'REVOKED')),
  recorded_by_principal_id text NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  UNIQUE (consultation_id, participant_identity, policy_version)
);

CREATE INDEX IF NOT EXISTS video_consultation_ai_consents_lookup_idx
  ON video_consultation_ai_consents (consultation_id, participant_identity, policy_version);

CREATE TABLE IF NOT EXISTS video_consultation_interpretation_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES video_consultations(id) ON DELETE CASCADE,
  room_name text NOT NULL,
  room_generation integer NOT NULL CHECK (room_generation > 0),
  interpretation_generation integer NOT NULL CHECK (interpretation_generation > 0),
  agent_execution_version integer NOT NULL CHECK (agent_execution_version > 0),
  authorization_revision bigint NOT NULL DEFAULT 1 CHECK (authorization_revision > 0),
  desired_state text NOT NULL CHECK (desired_state IN ('RUNNING', 'STOPPED')),
  status text NOT NULL CHECK (status IN (
    'DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING', 'STOPPED', 'FAILED', 'BUDGET_EXHAUSTED'
  )),
  provider_profile text NOT NULL CHECK (provider_profile IN ('DISABLED', 'INTEGRATED_REALTIME')),
  source_language text NOT NULL CHECK (source_language IN ('zh', 'en')),
  target_language text NOT NULL CHECK (target_language IN ('zh', 'en') AND target_language <> source_language),
  consent_policy_version text NOT NULL,
  agent_identity text NOT NULL,
  hosted_deployment_id uuid REFERENCES video_consultation_hosted_deployments(id) ON DELETE RESTRICT,
  dispatch_id text,
  exchange_available boolean NOT NULL DEFAULT true,
  job_capability_digest text,
  capability_expires_at timestamptz,
  maximum_ai_duration_seconds integer NOT NULL CHECK (maximum_ai_duration_seconds BETWEEN 60 AND 7200),
  reserved_microdollars bigint NOT NULL DEFAULT 0 CHECK (reserved_microdollars >= 0),
  consumed_microdollars bigint NOT NULL DEFAULT 0 CHECK (consumed_microdollars >= 0),
  failure_code text,
  started_at timestamptz,
  stopped_at timestamptz,
  created_by_principal_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (consultation_id, room_generation, interpretation_generation)
);

CREATE UNIQUE INDEX IF NOT EXISTS video_consultation_interpretation_jobs_one_active_idx
  ON video_consultation_interpretation_jobs (consultation_id, room_generation)
  WHERE desired_state = 'RUNNING' AND status IN ('DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING');

CREATE INDEX IF NOT EXISTS video_consultation_interpretation_jobs_capacity_idx
  ON video_consultation_interpretation_jobs (status)
  WHERE desired_state = 'RUNNING';

CREATE TABLE IF NOT EXISTS video_consultation_interpretation_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  job_id uuid NOT NULL REFERENCES video_consultation_interpretation_jobs(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN (
    'START', 'DISPATCH', 'BOOTSTRAP_EXCHANGE', 'ACTIVE', 'STOP', 'FAIL', 'COMPLETE',
    'AUTHORIZATION_EXPIRED', 'CONSENT_CHANGED', 'PROVIDER_SESSION_CHANGED', 'BUDGET_CHANGED'
  )),
  actor_type text NOT NULL CHECK (actor_type IN ('PRINCIPAL', 'AGENT', 'SYSTEM')),
  actor_id text,
  execution_version integer NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS video_consultation_interpretation_events_job_idx
  ON video_consultation_interpretation_events (job_id, created_at);

CREATE TABLE IF NOT EXISTS video_consultation_source_tracks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES video_consultation_interpretation_jobs(id) ON DELETE CASCADE,
  participant_identity text NOT NULL,
  track_sid text NOT NULL,
  track_source text NOT NULL CHECK (track_source = 'MICROPHONE'),
  expected_source_language text NOT NULL CHECK (expected_source_language IN ('zh', 'en')),
  target_language text NOT NULL CHECK (target_language IN ('zh', 'en') AND target_language <> expected_source_language),
  language_version integer NOT NULL DEFAULT 1 CHECK (language_version > 0),
  consent_version integer NOT NULL DEFAULT 1 CHECK (consent_version > 0),
  authorization_revision bigint NOT NULL DEFAULT 1 CHECK (authorization_revision > 0),
  authorized boolean NOT NULL DEFAULT false,
  set_by_principal_id text NOT NULL,
  set_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz NOT NULL,
  unpublished_at timestamptz,
  UNIQUE (job_id, track_sid)
);

CREATE TABLE IF NOT EXISTS video_consultation_provider_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES video_consultation_interpretation_jobs(id) ON DELETE CASCADE,
  source_track_id uuid NOT NULL REFERENCES video_consultation_source_tracks(id) ON DELETE CASCADE,
  provider text NOT NULL,
  provider_profile text NOT NULL,
  provider_session_reference text,
  room_generation integer NOT NULL,
  interpretation_generation integer NOT NULL,
  source_language text NOT NULL CHECK (source_language IN ('zh', 'en')),
  target_language text NOT NULL CHECK (target_language IN ('zh', 'en') AND target_language <> source_language),
  language_version integer NOT NULL CHECK (language_version > 0),
  agent_execution_version integer NOT NULL CHECK (agent_execution_version > 0),
  state text NOT NULL CHECK (state IN ('CREATING', 'ACTIVE', 'CLOSING', 'ORPHAN_WAIT', 'CLOSED', 'FAILED')),
  application_deadline_at timestamptz NOT NULL,
  provider_expires_at timestamptz,
  last_seen_at timestamptz,
  closed_at timestamptz,
  close_result text,
  orphan_risk boolean NOT NULL DEFAULT false,
  input_audio_milliseconds bigint NOT NULL DEFAULT 0 CHECK (input_audio_milliseconds >= 0),
  output_audio_milliseconds bigint NOT NULL DEFAULT 0 CHECK (output_audio_milliseconds >= 0),
  estimated_microdollars bigint NOT NULL DEFAULT 0 CHECK (estimated_microdollars >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS video_consultation_provider_sessions_active_fence_idx
  ON video_consultation_provider_sessions (job_id, source_track_id, interpretation_generation)
  WHERE state IN ('CREATING', 'ACTIVE', 'CLOSING', 'ORPHAN_WAIT');

CREATE INDEX IF NOT EXISTS video_consultation_provider_sessions_reconcile_idx
  ON video_consultation_provider_sessions (state, application_deadline_at)
  WHERE state IN ('CREATING', 'ACTIVE', 'CLOSING', 'ORPHAN_WAIT');

-- Completion can originate from the admin BFF, patient API, or a direct
-- application SQL path. Enforce fail-closed AI invalidation at the database
-- boundary so none of those paths can leave a watchdog capability authorized.
CREATE OR REPLACE FUNCTION invalidate_video_interpretation_on_consultation_close()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_job_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF NEW.status IN ('COMPLETED', 'CANCELLED', 'REJECTED')
     AND OLD.status IS DISTINCT FROM NEW.status THEN
    WITH affected AS (
      UPDATE video_consultation_interpretation_jobs
      SET desired_state = 'STOPPED',
          status = 'STOPPING',
          exchange_available = false,
          job_capability_digest = NULL,
          capability_expires_at = NULL,
          agent_execution_version = agent_execution_version + 1,
          authorization_revision = authorization_revision + 1,
          updated_at = now()
      WHERE consultation_id = NEW.id
        AND desired_state = 'RUNNING'
        AND status IN ('DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING')
      RETURNING id
    )
    SELECT COALESCE(array_agg(id), ARRAY[]::uuid[])
    INTO affected_job_ids
    FROM affected;

    IF cardinality(affected_job_ids) = 0 THEN
      RETURN NEW;
    END IF;

    UPDATE video_consultation_source_tracks track
    SET authorized = false,
        authorization_revision = authorization_revision + 1,
        unpublished_at = COALESCE(unpublished_at, now())
    WHERE track.job_id = ANY(affected_job_ids)
      AND track.authorized = true;

    UPDATE video_consultation_provider_sessions provider_session
    SET state = 'ORPHAN_WAIT', orphan_risk = true, updated_at = now()
    WHERE provider_session.job_id = ANY(affected_job_ids)
      AND provider_session.state IN ('CREATING', 'ACTIVE', 'CLOSING');

    INSERT INTO video_consultation_interpretation_events (
      job_id, event_type, actor_type, actor_id, execution_version, details
    )
    SELECT id, 'STOP', 'SYSTEM', NULL, agent_execution_version,
           jsonb_build_object('reason', 'consultation_status', 'status', NEW.status)
    FROM video_consultation_interpretation_jobs
    WHERE id = ANY(affected_job_ids);

    UPDATE video_consultation_interpretation_jobs
    SET status = 'STOPPED', stopped_at = COALESCE(stopped_at, now()), updated_at = now()
    WHERE id = ANY(affected_job_ids)
      AND desired_state = 'STOPPED' AND status = 'STOPPING';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS video_consultation_close_invalidates_interpretation
  ON video_consultations;
CREATE TRIGGER video_consultation_close_invalidates_interpretation
AFTER UPDATE OF status ON video_consultations
FOR EACH ROW
EXECUTE FUNCTION invalidate_video_interpretation_on_consultation_close();

-- Rotating or revoking a deployment secret is also an authority change. The
-- row lock used by bootstrap serializes with this trigger's UPDATE; whichever
-- transaction commits last leaves every old capability unusable.
CREATE OR REPLACE FUNCTION invalidate_video_interpretation_on_deployment_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_job_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF NEW.enabled = false
     OR NEW.revoked_at IS NOT NULL
     OR OLD.bootstrap_secret_digest IS DISTINCT FROM NEW.bootstrap_secret_digest THEN
    WITH affected AS (
      UPDATE video_consultation_interpretation_jobs
      SET desired_state = 'STOPPED',
          status = 'STOPPING',
          exchange_available = false,
          job_capability_digest = NULL,
          capability_expires_at = NULL,
          agent_execution_version = agent_execution_version + 1,
          authorization_revision = authorization_revision + 1,
          updated_at = now()
      WHERE hosted_deployment_id = NEW.id
        AND desired_state = 'RUNNING'
        AND status IN ('DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING')
      RETURNING id
    )
    SELECT COALESCE(array_agg(id), ARRAY[]::uuid[])
    INTO affected_job_ids
    FROM affected;

    IF cardinality(affected_job_ids) = 0 THEN
      RETURN NEW;
    END IF;

    UPDATE video_consultation_source_tracks track
    SET authorized = false,
        authorization_revision = authorization_revision + 1,
        unpublished_at = COALESCE(unpublished_at, now())
    WHERE track.job_id = ANY(affected_job_ids)
      AND track.authorized = true;

    UPDATE video_consultation_provider_sessions provider_session
    SET state = 'ORPHAN_WAIT', orphan_risk = true, updated_at = now()
    WHERE provider_session.job_id = ANY(affected_job_ids)
      AND provider_session.state IN ('CREATING', 'ACTIVE', 'CLOSING');

    INSERT INTO video_consultation_interpretation_events (
      job_id, event_type, actor_type, actor_id, execution_version, details
    )
    SELECT id, 'STOP', 'SYSTEM', NULL, agent_execution_version,
           jsonb_build_object('reason', 'deployment_authority_changed')
    FROM video_consultation_interpretation_jobs
    WHERE id = ANY(affected_job_ids);

    UPDATE video_consultation_interpretation_jobs
    SET status = 'STOPPED', stopped_at = COALESCE(stopped_at, now()), updated_at = now()
    WHERE id = ANY(affected_job_ids)
      AND desired_state = 'STOPPED' AND status = 'STOPPING';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS video_interpretation_deployment_change_invalidates_jobs
  ON video_consultation_hosted_deployments;
CREATE TRIGGER video_interpretation_deployment_change_invalidates_jobs
AFTER UPDATE OF enabled, revoked_at, bootstrap_secret_digest
ON video_consultation_hosted_deployments
FOR EACH ROW
EXECUTE FUNCTION invalidate_video_interpretation_on_deployment_change();

-- Video staging migration: 052_video_interpretation_provider_expiry.sql
-- Adds the monotonic consent epoch used to prevent stale grants, and supports
-- bounded, idempotent recovery of provider fences whose server-owned expiry
-- has elapsed. application_deadline_at remains an input cutoff only and is
-- deliberately not used as provider-closure evidence.
ALTER TABLE video_consultation_ai_consents
  ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 1;

DO $$
BEGIN
  ALTER TABLE video_consultation_ai_consents
    ADD CONSTRAINT video_consultation_ai_consents_version_positive CHECK (version > 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS video_consultation_provider_sessions_provider_expiry_idx
  ON video_consultation_provider_sessions (provider_expires_at)
  WHERE state IN ('CREATING', 'ACTIVE', 'CLOSING', 'ORPHAN_WAIT')
    AND provider_expires_at IS NOT NULL;

-- Video staging migration: 053_video_interpretation_launch_and_self_host.sql
-- Phase C/D readiness: explicit release approvals, enforceable budgets, and
-- optional self-host authority. This migration does not enable patient media
-- or select self-hosting; both remain separately reviewed runtime decisions.

CREATE TABLE IF NOT EXISTS video_interpretation_release_approvals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data_classification text NOT NULL CHECK (data_classification IN ('DEIDENTIFIED_EVALUATION', 'REAL_PATIENT')),
  provider text NOT NULL,
  provider_model text NOT NULL,
  provider_endpoint text NOT NULL,
  processing_region text NOT NULL,
  approval_reference text NOT NULL,
  contracts_approved boolean NOT NULL DEFAULT false,
  privacy_verified boolean NOT NULL DEFAULT false,
  observability_disabled boolean NOT NULL DEFAULT false,
  retention_verified boolean NOT NULL DEFAULT false,
  provider_rate_microdollars_per_minute bigint NOT NULL CHECK (provider_rate_microdollars_per_minute > 0),
  per_room_hard_limit_microdollars bigint NOT NULL CHECK (per_room_hard_limit_microdollars > 0),
  daily_hard_limit_microdollars bigint NOT NULL CHECK (daily_hard_limit_microdollars > 0),
  monthly_hard_limit_microdollars bigint NOT NULL CHECK (monthly_hard_limit_microdollars > 0),
  approved_by_principal_id text NOT NULL,
  approved_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (expires_at > approved_at)
);

CREATE INDEX IF NOT EXISTS video_interpretation_release_approvals_active_idx
  ON video_interpretation_release_approvals (data_classification, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS video_consultation_interpretation_allowlist (
  consultation_id uuid PRIMARY KEY REFERENCES video_consultations(id) ON DELETE CASCADE,
  release_approval_id uuid NOT NULL REFERENCES video_interpretation_release_approvals(id) ON DELETE RESTRICT,
  enabled boolean NOT NULL DEFAULT true,
  allowed_by_principal_id text NOT NULL,
  allowed_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (expires_at > allowed_at)
);

CREATE TABLE IF NOT EXISTS video_interpretation_self_hosts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  host_name text NOT NULL UNIQUE,
  bearer_secret_digest text NOT NULL,
  credential_version bigint NOT NULL DEFAULT 1 CHECK (credential_version > 0),
  max_jobs integer NOT NULL DEFAULT 1 CHECK (max_jobs = 1),
  enabled boolean NOT NULL DEFAULT true,
  created_by_principal_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  rotated_at timestamptz,
  last_heartbeat_at timestamptz,
  revoked_at timestamptz
);

-- Cross-process single-flight for the independently scheduled hosted and
-- self-hosted cleanup passes. A lease is intentionally recoverable after a
-- worker/API crash; no database transaction is held across LiveKit calls.
CREATE TABLE IF NOT EXISTS video_interpretation_reconcile_leases (
  profile text PRIMARY KEY CHECK (profile IN ('HOSTED', 'SELF_HOSTED_FENCE', 'SELF_HOSTED_CLEANUP')),
  owner_id uuid,
  lease_expires_at timestamptz NOT NULL DEFAULT '-infinity',
  run_started_at timestamptz,
  last_succeeded_at timestamptz,
  last_failed_at timestamptz,
  consecutive_failures integer NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
  last_error_code text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((owner_id IS NULL) = (run_started_at IS NULL))
);

ALTER TABLE video_consultation_interpretation_jobs
  ADD COLUMN IF NOT EXISTS runtime_profile text NOT NULL DEFAULT 'HOSTED_AGENT_V1',
  ADD COLUMN IF NOT EXISTS data_classification text NOT NULL DEFAULT 'DEIDENTIFIED_EVALUATION',
  ADD COLUMN IF NOT EXISTS release_approval_id uuid REFERENCES video_interpretation_release_approvals(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS provider_model text,
  ADD COLUMN IF NOT EXISTS provider_endpoint text,
  ADD COLUMN IF NOT EXISTS provider_rate_microdollars_per_minute bigint,
  ADD COLUMN IF NOT EXISTS hard_budget_microdollars bigint,
  ADD COLUMN IF NOT EXISTS self_host_id uuid REFERENCES video_interpretation_self_hosts(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS self_host_credential_version bigint,
  ADD COLUMN IF NOT EXISTS lease_version bigint,
  ADD COLUMN IF NOT EXISTS lease_expires_at timestamptz,
  ADD COLUMN IF NOT EXISTS self_host_claim_deadline_at timestamptz,
  ADD COLUMN IF NOT EXISTS agent_identity_revoked_at timestamptz,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_deleted_at timestamptz,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_creation_pending boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_correlation_id text,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_attempt_execution_version bigint,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_attempt_agent_identity text,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_absence_observed_at timestamptz,
  ADD COLUMN IF NOT EXISTS hosted_dispatch_creation_deadline_at timestamptz,
  ADD COLUMN IF NOT EXISTS hosted_bootstrap_deadline_at timestamptz;

DO $$
BEGIN
  ALTER TABLE video_consultation_interpretation_jobs
    ADD CONSTRAINT video_interpretation_jobs_runtime_profile_check
    CHECK (runtime_profile IN ('HOSTED_AGENT_V1', 'SELF_HOSTED_AGENT'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE video_consultation_interpretation_jobs
    ADD CONSTRAINT video_interpretation_self_host_claim_deadline_check
    CHECK (
      runtime_profile <> 'SELF_HOSTED_AGENT'
      OR desired_state <> 'RUNNING'
      OR status <> 'DISPATCHING'
      OR self_host_claim_deadline_at IS NOT NULL
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE video_consultation_interpretation_jobs
    ADD CONSTRAINT video_interpretation_jobs_data_classification_check
    CHECK (data_classification IN ('DEIDENTIFIED_EVALUATION', 'REAL_PATIENT'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE video_consultation_interpretation_jobs
    ADD CONSTRAINT video_interpretation_jobs_budget_positive_check
    CHECK (
      (provider_rate_microdollars_per_minute IS NULL OR provider_rate_microdollars_per_minute > 0)
      AND (hard_budget_microdollars IS NULL OR hard_budget_microdollars > 0)
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS video_interpretation_self_host_claim_idx
  ON video_consultation_interpretation_jobs (self_host_claim_deadline_at, created_at)
  WHERE runtime_profile = 'SELF_HOSTED_AGENT'
    AND desired_state = 'RUNNING'
    AND status = 'DISPATCHING';

CREATE INDEX IF NOT EXISTS video_interpretation_self_host_lease_idx
  ON video_consultation_interpretation_jobs (lease_expires_at)
  WHERE runtime_profile = 'SELF_HOSTED_AGENT'
    AND desired_state = 'RUNNING'
    AND status IN ('AWAITING_AGENT', 'ACTIVE');

CREATE INDEX IF NOT EXISTS video_interpretation_self_host_cleanup_idx
  ON video_consultation_interpretation_jobs (updated_at)
  WHERE runtime_profile = 'SELF_HOSTED_AGENT'
    AND status = 'STOPPING';

CREATE INDEX IF NOT EXISTS video_interpretation_hosted_cleanup_idx
  ON video_consultation_interpretation_jobs (updated_at)
  WHERE runtime_profile = 'HOSTED_AGENT_V1'
    AND status = 'STOPPING';

-- Migration 051 predates durable runtime cleanup. Leave both runtime profiles
-- in STOPPING until the independent reconciler proves dispatch/token/identity
-- cleanup and provider-fence finality.
CREATE OR REPLACE FUNCTION invalidate_video_interpretation_on_consultation_close()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_job_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF NEW.status IN ('COMPLETED', 'CANCELLED', 'REJECTED')
     AND OLD.status IS DISTINCT FROM NEW.status THEN
    WITH affected AS (
      UPDATE video_consultation_interpretation_jobs
      SET desired_state = 'STOPPED',
          status = 'STOPPING',
          exchange_available = false,
          job_capability_digest = NULL,
          capability_expires_at = NULL,
          agent_execution_version = agent_execution_version + 1,
          authorization_revision = authorization_revision + 1,
          lease_expires_at = CASE WHEN runtime_profile = 'SELF_HOSTED_AGENT' THEN NULL ELSE lease_expires_at END,
          agent_identity_revoked_at = CASE
            WHEN runtime_profile = 'SELF_HOSTED_AGENT' THEN NULL ELSE agent_identity_revoked_at
          END,
          hosted_dispatch_deleted_at = CASE
            WHEN runtime_profile = 'HOSTED_AGENT_V1' THEN NULL ELSE hosted_dispatch_deleted_at
          END,
          failure_code = 'CONSULTATION_CLOSED',
          updated_at = now()
      WHERE consultation_id = NEW.id
        AND desired_state = 'RUNNING'
        AND status IN ('DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING')
      RETURNING id
    )
    SELECT COALESCE(array_agg(id), ARRAY[]::uuid[])
    INTO affected_job_ids
    FROM affected;

    IF cardinality(affected_job_ids) = 0 THEN RETURN NEW; END IF;

    UPDATE video_consultation_source_tracks track
    SET authorized = false,
        authorization_revision = authorization_revision + 1,
        unpublished_at = COALESCE(unpublished_at, now())
    WHERE track.job_id = ANY(affected_job_ids) AND track.authorized = true;

    UPDATE video_consultation_provider_sessions provider_session
    SET state = 'ORPHAN_WAIT', orphan_risk = true, updated_at = now()
    WHERE provider_session.job_id = ANY(affected_job_ids)
      AND provider_session.state IN ('CREATING', 'ACTIVE', 'CLOSING');

    INSERT INTO video_consultation_interpretation_events (
      job_id, event_type, actor_type, actor_id, execution_version, details
    )
    SELECT id, 'STOP', 'SYSTEM', NULL, agent_execution_version,
           jsonb_build_object('reason', 'consultation_status', 'status', NEW.status)
    FROM video_consultation_interpretation_jobs
    WHERE id = ANY(affected_job_ids);

  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION invalidate_video_interpretation_on_deployment_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  affected_job_ids uuid[] := ARRAY[]::uuid[];
BEGIN
  IF NEW.enabled = false
     OR NEW.revoked_at IS NOT NULL
     OR OLD.bootstrap_secret_digest IS DISTINCT FROM NEW.bootstrap_secret_digest THEN
    WITH affected AS (
      UPDATE video_consultation_interpretation_jobs
      SET desired_state = 'STOPPED', status = 'STOPPING',
          exchange_available = false, job_capability_digest = NULL,
          capability_expires_at = NULL,
          agent_execution_version = agent_execution_version + 1,
          authorization_revision = authorization_revision + 1,
          hosted_dispatch_deleted_at = NULL,
          agent_identity_revoked_at = NULL,
          failure_code = 'HOSTED_DEPLOYMENT_AUTHORITY_CHANGED', updated_at = now()
      WHERE hosted_deployment_id = NEW.id
        AND desired_state = 'RUNNING'
        AND status IN ('DISPATCHING', 'AWAITING_AGENT', 'ACTIVE', 'STOPPING')
      RETURNING id
    )
    SELECT COALESCE(array_agg(id), ARRAY[]::uuid[])
    INTO affected_job_ids
    FROM affected;

    IF cardinality(affected_job_ids) = 0 THEN RETURN NEW; END IF;

    UPDATE video_consultation_source_tracks track
    SET authorized = false,
        authorization_revision = authorization_revision + 1,
        unpublished_at = COALESCE(unpublished_at, now())
    WHERE track.job_id = ANY(affected_job_ids) AND track.authorized = true;

    UPDATE video_consultation_provider_sessions provider_session
    SET state = 'ORPHAN_WAIT', orphan_risk = true, updated_at = now()
    WHERE provider_session.job_id = ANY(affected_job_ids)
      AND provider_session.state IN ('CREATING', 'ACTIVE', 'CLOSING');

    INSERT INTO video_consultation_interpretation_events (
      job_id, event_type, actor_type, actor_id, execution_version, details
    )
    SELECT id, 'STOP', 'SYSTEM', NULL, agent_execution_version,
           jsonb_build_object('reason', 'deployment_authority_changed')
    FROM video_consultation_interpretation_jobs
    WHERE id = ANY(affected_job_ids);
  END IF;
  RETURN NEW;
END;
$$;

ALTER TABLE video_consultation_interpretation_events
  DROP CONSTRAINT IF EXISTS video_consultation_interpretation_events_event_type_check;

ALTER TABLE video_consultation_interpretation_events
  ADD CONSTRAINT video_consultation_interpretation_events_event_type_check CHECK (event_type IN (
    'START', 'DISPATCH', 'BOOTSTRAP_EXCHANGE', 'ACTIVE', 'STOP', 'FAIL', 'COMPLETE',
    'AUTHORIZATION_EXPIRED', 'CONSENT_CHANGED', 'PROVIDER_SESSION_CHANGED', 'BUDGET_CHANGED',
    'HUMAN_ESCALATION_REQUESTED', 'CLAIM', 'HEARTBEAT', 'TAKEOVER',
    'APPLICATION_DEADLINE_ELAPSED'
  ));

-- Video staging migration: 054_video_interpretation_self_host_single_job.sql
-- The supplied V1 supervisor runs one room for the lifetime of each claim.
-- Normalize any pre-release rows created from an earlier draft and keep API
-- capacity claims aligned with the executable supervisor.
UPDATE video_interpretation_self_hosts
SET max_jobs = 1
WHERE max_jobs <> 1;

ALTER TABLE video_interpretation_self_hosts
  DROP CONSTRAINT IF EXISTS video_interpretation_self_hosts_max_jobs_check;

ALTER TABLE video_interpretation_self_hosts
  ADD CONSTRAINT video_interpretation_self_hosts_max_jobs_check
  CHECK (max_jobs = 1);

-- Video staging migration: 055_video_consultation_participants.sql
-- Consent recording admits only identities that are currently in the room,
-- the canonical host, or the authenticated operator. Production historically
-- received this table outside tracked SQL migrations; keep this migration
-- idempotent for both an existing deployment and the video-only staging schema.

CREATE TABLE IF NOT EXISTS video_consultation_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES video_consultations(id) ON DELETE CASCADE,
  identity text NOT NULL,
  display_name text,
  role text CHECK (role IS NULL OR role IN ('PATIENT', 'DOCTOR', 'COORDINATOR', 'GUEST')),
  joined_at timestamptz NOT NULL DEFAULT now(),
  left_at timestamptz,
  duration_seconds integer CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
  metadata jsonb
);

CREATE INDEX IF NOT EXISTS video_consultation_participants_active_idx
  ON video_consultation_participants (consultation_id, identity)
  WHERE left_at IS NULL;

-- Video staging migration: 056_video_interpretation_synthetic_e2e_approval.sql
-- A synthetic E2E approval is deliberately not a privacy/contract release.
-- Bind it one-to-one to a short-lived, server-recognizable synthetic
-- consultation so false privacy attestations can never authorize another room.

ALTER TABLE video_interpretation_release_approvals
  ADD COLUMN IF NOT EXISTS approval_scope text NOT NULL DEFAULT 'RELEASE',
  ADD COLUMN IF NOT EXISTS synthetic_consultation_id uuid
    REFERENCES video_consultations(id) ON DELETE CASCADE;

DO $$
BEGIN
  ALTER TABLE video_interpretation_release_approvals
    ADD CONSTRAINT video_interpretation_release_approvals_scope_check CHECK (
      (
        approval_scope = 'RELEASE'
        AND synthetic_consultation_id IS NULL
      )
      OR (
        approval_scope = 'SYNTHETIC_E2E'
        AND synthetic_consultation_id IS NOT NULL
        AND data_classification = 'DEIDENTIFIED_EVALUATION'
        AND contracts_approved = false
        AND privacy_verified = false
        AND observability_disabled = false
        AND retention_verified = false
        AND expires_at <= approved_at + interval '30 minutes'
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS video_interpretation_release_approvals_synthetic_consultation_idx
  ON video_interpretation_release_approvals (synthetic_consultation_id)
  WHERE approval_scope = 'SYNTHETIC_E2E' AND revoked_at IS NULL;

CREATE OR REPLACE FUNCTION video_interpretation_is_synthetic_e2e_consultation(
  candidate_consultation_id uuid,
  evaluated_at timestamptz DEFAULT now()
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  consultation public.video_consultations%ROWTYPE;
  metadata_expiry timestamptz;
BEGIN
  SELECT * INTO consultation
  FROM public.video_consultations
  WHERE id = candidate_consultation_id;

  IF NOT FOUND
    OR consultation.status NOT IN ('SCHEDULED', 'IN_PROGRESS')
    OR consultation.room_name !~ '^medora-deidentified-e2e-[0-9a-f]{16}$'
    OR consultation.case_id IS NOT NULL
    OR consultation.patient_id IS NOT NULL
    OR consultation.patient_name IS NOT NULL
    OR consultation.patient_email IS NOT NULL
    OR consultation.metadata IS NULL
    OR consultation.metadata -> 'synthetic' IS DISTINCT FROM 'true'::jsonb
    OR consultation.metadata ->> 'classification' IS DISTINCT FROM 'DEIDENTIFIED_EVALUATION'
    OR jsonb_typeof(consultation.metadata -> 'expiresAt') IS DISTINCT FROM 'string' THEN
    RETURN false;
  END IF;

  BEGIN
    metadata_expiry := (consultation.metadata ->> 'expiresAt')::timestamptz;
  EXCEPTION WHEN invalid_datetime_format OR datetime_field_overflow THEN
    RETURN false;
  END;

  RETURN metadata_expiry > evaluated_at
    AND metadata_expiry <= evaluated_at + interval '30 minutes';
END;
$$;

CREATE OR REPLACE FUNCTION video_interpretation_approval_authorized(
  candidate_approval_id uuid,
  candidate_consultation_id uuid,
  candidate_data_classification text,
  evaluated_at timestamptz DEFAULT now()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.video_interpretation_release_approvals approval
    WHERE approval.id = candidate_approval_id
      AND approval.data_classification = candidate_data_classification
      AND approval.revoked_at IS NULL
      AND approval.expires_at > evaluated_at
      AND (
        (
          approval.approval_scope = 'RELEASE'
          AND approval.synthetic_consultation_id IS NULL
          AND approval.privacy_verified = true
          AND approval.observability_disabled = true
          AND approval.retention_verified = true
          AND (candidate_data_classification <> 'REAL_PATIENT'
            OR approval.contracts_approved = true)
        )
        OR (
          approval.approval_scope = 'SYNTHETIC_E2E'
          AND candidate_data_classification = 'DEIDENTIFIED_EVALUATION'
          AND approval.synthetic_consultation_id = candidate_consultation_id
          AND approval.contracts_approved = false
          AND approval.privacy_verified = false
          AND approval.observability_disabled = false
          AND approval.retention_verified = false
          AND approval.expires_at <= approval.approved_at + interval '30 minutes'
          AND public.video_interpretation_is_synthetic_e2e_consultation(
            candidate_consultation_id,
            evaluated_at
          )
        )
      )
  );
$$;

REVOKE ALL ON FUNCTION video_interpretation_is_synthetic_e2e_consultation(uuid, timestamptz)
  FROM PUBLIC;
REVOKE ALL ON FUNCTION video_interpretation_approval_authorized(uuid, uuid, text, timestamptz)
  FROM PUBLIC;

CREATE TABLE IF NOT EXISTS video_interpretation_schema_migrations (
  name text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO video_interpretation_schema_migrations (name)
VALUES
  ('video-staging-auth.sql'),
  ('050_video_consultations.sql'),
  ('051_video_interpretation_control_plane.sql'),
  ('052_video_interpretation_provider_expiry.sql'),
  ('053_video_interpretation_launch_and_self_host.sql'),
  ('054_video_interpretation_self_host_single_job.sql'),
  ('055_video_consultation_participants.sql'),
  ('056_video_interpretation_synthetic_e2e_approval.sql')
ON CONFLICT (name) DO NOTHING;

-- Video staging lockdown: video-staging-data-api-lockdown.sql
-- The video staging API uses a direct PostgreSQL connection. Supabase REST and
-- GraphQL roles must never reach identity or interpretation authority tables,
-- even on projects that retain legacy public-schema default grants.

DO $$
DECLARE
  table_name text;
  target_schema text := current_schema();
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users',
    'video_consultations',
    'video_consultation_participants',
    'video_consultation_hosted_deployments',
    'video_consultation_ai_consents',
    'video_consultation_interpretation_jobs',
    'video_consultation_interpretation_events',
    'video_consultation_source_tracks',
    'video_consultation_provider_sessions',
    'video_interpretation_release_approvals',
    'video_consultation_interpretation_allowlist',
    'video_interpretation_self_hosts',
    'video_interpretation_reconcile_leases',
    'video_interpretation_schema_migrations'
  ]
  LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',
      target_schema,
      table_name
    );
  END LOOP;
END $$;

DO $$
DECLARE
  role_name text;
  target_schema text := current_schema();
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated', 'service_role']
  LOOP
    IF to_regrole(role_name) IS NOT NULL THEN
      EXECUTE format(
        'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA %I FROM %I',
        target_schema,
        role_name
      );
      EXECUTE format(
        'REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA %I FROM %I',
        target_schema,
        role_name
      );
      EXECUTE format(
        'REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA %I FROM %I',
        target_schema,
        role_name
      );
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE ALL PRIVILEGES ON TABLES FROM %I',
        target_schema,
        role_name
      );
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE ALL PRIVILEGES ON SEQUENCES FROM %I',
        target_schema,
        role_name
      );
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE EXECUTE ON FUNCTIONS FROM %I',
        target_schema,
        role_name
      );
    END IF;
  END LOOP;
END $$;

DO $$
DECLARE
  target_schema text := current_schema();
BEGIN
  EXECUTE format(
    'REVOKE EXECUTE ON FUNCTION %I.invalidate_video_interpretation_on_consultation_close() FROM PUBLIC',
    target_schema
  );
  EXECUTE format(
    'REVOKE EXECUTE ON FUNCTION %I.invalidate_video_interpretation_on_deployment_change() FROM PUBLIC',
    target_schema
  );
  EXECUTE format(
    'REVOKE EXECUTE ON FUNCTION %I.video_interpretation_is_synthetic_e2e_consultation(uuid, timestamptz) FROM PUBLIC',
    target_schema
  );
  EXECUTE format(
    'REVOKE EXECUTE ON FUNCTION %I.video_interpretation_approval_authorized(uuid, uuid, text, timestamptz) FROM PUBLIC',
    target_schema
  );
  EXECUTE format(
    'ALTER DEFAULT PRIVILEGES IN SCHEMA %I REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC',
    target_schema
  );
END $$;

-- Fail the bootstrap if any Supabase Data API role still inherits authority on
-- a protected table or trigger function.
DO $$
DECLARE
  role_name text;
  table_name text;
  function_name text;
  sequence_name text;
  target_schema text := current_schema();
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated', 'service_role']
  LOOP
    IF to_regrole(role_name) IS NULL THEN
      CONTINUE;
    END IF;

    FOREACH table_name IN ARRAY ARRAY[
      'users',
      'video_consultations',
      'video_consultation_participants',
      'video_consultation_hosted_deployments',
      'video_consultation_ai_consents',
      'video_consultation_interpretation_jobs',
      'video_consultation_interpretation_events',
      'video_consultation_source_tracks',
      'video_consultation_provider_sessions',
      'video_interpretation_release_approvals',
      'video_consultation_interpretation_allowlist',
      'video_interpretation_self_hosts',
      'video_interpretation_reconcile_leases',
      'video_interpretation_schema_migrations'
    ]
    LOOP
      IF has_table_privilege(
        role_name,
        format('%I.%I', target_schema, table_name),
        'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'
      ) THEN
        RAISE EXCEPTION 'Data API role % retains privileges on %.%',
          role_name, target_schema, table_name;
      END IF;
    END LOOP;

    FOR sequence_name IN
      SELECT c.relname
      FROM pg_class AS c
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = target_schema AND c.relkind = 'S'
    LOOP
      IF has_sequence_privilege(
        role_name,
        format('%I.%I', target_schema, sequence_name),
        'USAGE,SELECT,UPDATE'
      ) THEN
        RAISE EXCEPTION 'Data API role % retains privileges on sequence %.%',
          role_name, target_schema, sequence_name;
      END IF;
    END LOOP;

    FOREACH function_name IN ARRAY ARRAY[
      format('%I.invalidate_video_interpretation_on_consultation_close()', target_schema),
      format('%I.invalidate_video_interpretation_on_deployment_change()', target_schema),
      format('%I.video_interpretation_is_synthetic_e2e_consultation(uuid,timestamptz)', target_schema),
      format('%I.video_interpretation_approval_authorized(uuid,uuid,text,timestamptz)', target_schema)
    ]
    LOOP
      IF has_function_privilege(role_name, function_name, 'EXECUTE') THEN
        RAISE EXCEPTION 'Data API role % retains execute on %',
          role_name, function_name;
      END IF;
    END LOOP;
  END LOOP;
END $$;

INSERT INTO video_interpretation_schema_migrations (name)
VALUES
  ('video-staging-data-api-lockdown.sql')
ON CONFLICT (name) DO NOTHING;
