import { OpenAPIHono } from '@hono/zod-openapi';
import caseRoutes from './cases.routes.js';
import documentRoutes from './documents.routes.js';
import progressRoutes from './progress.routes.js';
import hospitalRoutes from './hospitals.routes.js';
import conversationRoutes from './conversations.routes.js';
import messageRoutes from './messages.routes.js';
import consultationRoutes from './consultations.routes.js';
import materialsRoutes from './materials.routes.js';
import hospitalContactRoutes from './hospital-contacts.routes.js';
import quoteRoutes from './quotes.routes.js';
import eventRoutes from './events.routes.js';
import ticketRoutes from './tickets.routes.js';
import packageRoutes from './packages.routes.js';
import orderRoutes from './orders.routes.js';

const router = new OpenAPIHono();
router.route('/', caseRoutes);
router.route('/', documentRoutes);
router.route('/', progressRoutes);
router.route('/', hospitalRoutes);
router.route('/', conversationRoutes);
router.route('/', messageRoutes);
router.route('/', consultationRoutes);
router.route('/', materialsRoutes);
router.route('/', hospitalContactRoutes);
router.route('/', quoteRoutes);
router.route('/', eventRoutes);
router.route('/', ticketRoutes);
router.route('/', packageRoutes);
router.route('/', orderRoutes);

export default router;
