-- Module 2: Events / Timeline

CREATE TYPE "CaseEventType" AS ENUM (
  'CASE_CREATED', 'CASE_DISTRIBUTED', 'CASE_ASSIGNED', 'CASE_STATUS_CHANGED', 'CASE_STAGE_ADVANCED',
  'HOSPITALS_SELECTED', 'HOSPITAL_REPLIED', 'HOSPITAL_NEED_INFO', 'HOSPITAL_REMOVED',
  'QUOTE_SENT', 'QUOTE_ACCEPTED', 'QUOTE_REJECTED', 'QUOTE_EXPIRED', 'QUOTE_RESENT',
  'MESSAGE_SENT', 'MESSAGE_RECEIVED',
  'QUESTIONNAIRE_SUBMITTED', 'CONSULTATION_SCHEDULED', 'CONSULTATION_COMPLETED',
  'DOCUMENT_UPLOADED',
  'ORDER_PLACED', 'ORDER_STATUS_CHANGED',
  'MILESTONE_ADDED', 'MILESTONE_UPDATED', 'JOURNEY_UPDATED',
  'TICKET_CREATED', 'TICKET_RESOLVED',
  'AI_SUMMARY_GENERATED'
);

CREATE TYPE "ActorType" AS ENUM ('PATIENT', 'HOSPITAL', 'ADMIN', 'SYSTEM');

CREATE TABLE case_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES cases(id),
  event_type "CaseEventType" NOT NULL,
  actor_type "ActorType" NOT NULL,
  actor_id UUID,
  event_data JSONB,
  is_visible_to_patient BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_case_events_case_created ON case_events(case_id, created_at DESC);
CREATE INDEX idx_case_events_type ON case_events(event_type, created_at DESC);
